// Code generated by ent, DO NOT EDIT.

package customdomainuser

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the customdomainuser type in the database.
	Label = "custom_domain_user"
	// FieldCustomDomainID holds the string denoting the custom_domain_id field in the database.
	FieldCustomDomainID = "custom_domain_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeCustomDomain holds the string denoting the custom_domain edge name in mutations.
	EdgeCustomDomain = "custom_domain"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// CustomDomainFieldID holds the string denoting the ID field of the CustomDomain.
	CustomDomainFieldID = "id"
	// UserFieldID holds the string denoting the ID field of the User.
	UserFieldID = "id"
	// Table holds the table name of the customdomainuser in the database.
	Table = "custom_domain_users"
	// CustomDomainTable is the table that holds the custom_domain relation/edge.
	CustomDomainTable = "custom_domain_users"
	// CustomDomainInverseTable is the table name for the CustomDomain entity.
	// It exists in this package in order to avoid circular dependency with the "customdomain" package.
	CustomDomainInverseTable = "custom_domains"
	// CustomDomainColumn is the table column denoting the custom_domain relation/edge.
	CustomDomainColumn = "custom_domain_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "custom_domain_users"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for customdomainuser fields.
var Columns = []string{
	FieldCustomDomainID,
	FieldUserID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the CustomDomainUser queries.
type OrderOption func(*sql.Selector)

// ByCustomDomainID orders the results by the custom_domain_id field.
func ByCustomDomainID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCustomDomainID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCustomDomainField orders the results by custom_domain field.
func ByCustomDomainField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCustomDomainStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newCustomDomainStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, CustomDomainColumn),
		sqlgraph.To(CustomDomainInverseTable, CustomDomainFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, CustomDomainTable, CustomDomainColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, UserColumn),
		sqlgraph.To(UserInverseTable, UserFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
	)
}
