// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/customdomain"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CustomDomainCreate is the builder for creating a CustomDomain entity.
type CustomDomainCreate struct {
	config
	mutation *CustomDomainMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *CustomDomainCreate) SetCreatedAt(v time.Time) *CustomDomainCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CustomDomainCreate) SetNillableCreatedAt(v *time.Time) *CustomDomainCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CustomDomainCreate) SetUpdatedAt(v time.Time) *CustomDomainCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CustomDomainCreate) SetNillableUpdatedAt(v *time.Time) *CustomDomainCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *CustomDomainCreate) SetDeletedAt(v time.Time) *CustomDomainCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *CustomDomainCreate) SetNillableDeletedAt(v *time.Time) *CustomDomainCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CustomDomainCreate) SetUserID(v int64) *CustomDomainCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAllUsers sets the "all_users" field.
func (_c *CustomDomainCreate) SetAllUsers(v bool) *CustomDomainCreate {
	_c.mutation.SetAllUsers(v)
	return _c
}

// SetNillableAllUsers sets the "all_users" field if the given value is not nil.
func (_c *CustomDomainCreate) SetNillableAllUsers(v *bool) *CustomDomainCreate {
	if v != nil {
		_c.SetAllUsers(*v)
	}
	return _c
}

// SetDomain sets the "domain" field.
func (_c *CustomDomainCreate) SetDomain(v string) *CustomDomainCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *CustomDomainCreate) SetStatus(v string) *CustomDomainCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *CustomDomainCreate) SetNillableStatus(v *string) *CustomDomainCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetVerificationToken sets the "verification_token" field.
func (_c *CustomDomainCreate) SetVerificationToken(v string) *CustomDomainCreate {
	_c.mutation.SetVerificationToken(v)
	return _c
}

// SetVerificationTxtName sets the "verification_txt_name" field.
func (_c *CustomDomainCreate) SetVerificationTxtName(v string) *CustomDomainCreate {
	_c.mutation.SetVerificationTxtName(v)
	return _c
}

// SetVerificationTxtValue sets the "verification_txt_value" field.
func (_c *CustomDomainCreate) SetVerificationTxtValue(v string) *CustomDomainCreate {
	_c.mutation.SetVerificationTxtValue(v)
	return _c
}

// SetCnameTarget sets the "cname_target" field.
func (_c *CustomDomainCreate) SetCnameTarget(v string) *CustomDomainCreate {
	_c.mutation.SetCnameTarget(v)
	return _c
}

// SetNillableCnameTarget sets the "cname_target" field if the given value is not nil.
func (_c *CustomDomainCreate) SetNillableCnameTarget(v *string) *CustomDomainCreate {
	if v != nil {
		_c.SetCnameTarget(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *CustomDomainCreate) SetLastError(v string) *CustomDomainCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *CustomDomainCreate) SetNillableLastError(v *string) *CustomDomainCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetVerifiedAt sets the "verified_at" field.
func (_c *CustomDomainCreate) SetVerifiedAt(v time.Time) *CustomDomainCreate {
	_c.mutation.SetVerifiedAt(v)
	return _c
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_c *CustomDomainCreate) SetNillableVerifiedAt(v *time.Time) *CustomDomainCreate {
	if v != nil {
		_c.SetVerifiedAt(*v)
	}
	return _c
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_c *CustomDomainCreate) SetLastCheckedAt(v time.Time) *CustomDomainCreate {
	_c.mutation.SetLastCheckedAt(v)
	return _c
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_c *CustomDomainCreate) SetNillableLastCheckedAt(v *time.Time) *CustomDomainCreate {
	if v != nil {
		_c.SetLastCheckedAt(*v)
	}
	return _c
}

// SetDisabledAt sets the "disabled_at" field.
func (_c *CustomDomainCreate) SetDisabledAt(v time.Time) *CustomDomainCreate {
	_c.mutation.SetDisabledAt(v)
	return _c
}

// SetNillableDisabledAt sets the "disabled_at" field if the given value is not nil.
func (_c *CustomDomainCreate) SetNillableDisabledAt(v *time.Time) *CustomDomainCreate {
	if v != nil {
		_c.SetDisabledAt(*v)
	}
	return _c
}

// SetDisabledReason sets the "disabled_reason" field.
func (_c *CustomDomainCreate) SetDisabledReason(v string) *CustomDomainCreate {
	_c.mutation.SetDisabledReason(v)
	return _c
}

// SetNillableDisabledReason sets the "disabled_reason" field if the given value is not nil.
func (_c *CustomDomainCreate) SetNillableDisabledReason(v *string) *CustomDomainCreate {
	if v != nil {
		_c.SetDisabledReason(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CustomDomainCreate) SetUser(v *User) *CustomDomainCreate {
	return _c.SetUserID(v.ID)
}

// AddAuthorizedUserIDs adds the "authorized_users" edge to the User entity by IDs.
func (_c *CustomDomainCreate) AddAuthorizedUserIDs(ids ...int64) *CustomDomainCreate {
	_c.mutation.AddAuthorizedUserIDs(ids...)
	return _c
}

// AddAuthorizedUsers adds the "authorized_users" edges to the User entity.
func (_c *CustomDomainCreate) AddAuthorizedUsers(v ...*User) *CustomDomainCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAuthorizedUserIDs(ids...)
}

// Mutation returns the CustomDomainMutation object of the builder.
func (_c *CustomDomainCreate) Mutation() *CustomDomainMutation {
	return _c.mutation
}

// Save creates the CustomDomain in the database.
func (_c *CustomDomainCreate) Save(ctx context.Context) (*CustomDomain, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CustomDomainCreate) SaveX(ctx context.Context) *CustomDomain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomDomainCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomDomainCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CustomDomainCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if customdomain.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized customdomain.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := customdomain.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if customdomain.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized customdomain.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := customdomain.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.AllUsers(); !ok {
		v := customdomain.DefaultAllUsers
		_c.mutation.SetAllUsers(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := customdomain.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *CustomDomainCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CustomDomain.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "CustomDomain.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CustomDomain.user_id"`)}
	}
	if _, ok := _c.mutation.AllUsers(); !ok {
		return &ValidationError{Name: "all_users", err: errors.New(`ent: missing required field "CustomDomain.all_users"`)}
	}
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "CustomDomain.domain"`)}
	}
	if v, ok := _c.mutation.Domain(); ok {
		if err := customdomain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "CustomDomain.domain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "CustomDomain.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := customdomain.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CustomDomain.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VerificationToken(); !ok {
		return &ValidationError{Name: "verification_token", err: errors.New(`ent: missing required field "CustomDomain.verification_token"`)}
	}
	if v, ok := _c.mutation.VerificationToken(); ok {
		if err := customdomain.VerificationTokenValidator(v); err != nil {
			return &ValidationError{Name: "verification_token", err: fmt.Errorf(`ent: validator failed for field "CustomDomain.verification_token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VerificationTxtName(); !ok {
		return &ValidationError{Name: "verification_txt_name", err: errors.New(`ent: missing required field "CustomDomain.verification_txt_name"`)}
	}
	if v, ok := _c.mutation.VerificationTxtName(); ok {
		if err := customdomain.VerificationTxtNameValidator(v); err != nil {
			return &ValidationError{Name: "verification_txt_name", err: fmt.Errorf(`ent: validator failed for field "CustomDomain.verification_txt_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VerificationTxtValue(); !ok {
		return &ValidationError{Name: "verification_txt_value", err: errors.New(`ent: missing required field "CustomDomain.verification_txt_value"`)}
	}
	if v, ok := _c.mutation.VerificationTxtValue(); ok {
		if err := customdomain.VerificationTxtValueValidator(v); err != nil {
			return &ValidationError{Name: "verification_txt_value", err: fmt.Errorf(`ent: validator failed for field "CustomDomain.verification_txt_value": %w`, err)}
		}
	}
	if v, ok := _c.mutation.CnameTarget(); ok {
		if err := customdomain.CnameTargetValidator(v); err != nil {
			return &ValidationError{Name: "cname_target", err: fmt.Errorf(`ent: validator failed for field "CustomDomain.cname_target": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CustomDomain.user"`)}
	}
	return nil
}

func (_c *CustomDomainCreate) sqlSave(ctx context.Context) (*CustomDomain, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CustomDomainCreate) createSpec() (*CustomDomain, *sqlgraph.CreateSpec) {
	var (
		_node = &CustomDomain{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(customdomain.Table, sqlgraph.NewFieldSpec(customdomain.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(customdomain.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(customdomain.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(customdomain.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.AllUsers(); ok {
		_spec.SetField(customdomain.FieldAllUsers, field.TypeBool, value)
		_node.AllUsers = value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(customdomain.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(customdomain.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.VerificationToken(); ok {
		_spec.SetField(customdomain.FieldVerificationToken, field.TypeString, value)
		_node.VerificationToken = value
	}
	if value, ok := _c.mutation.VerificationTxtName(); ok {
		_spec.SetField(customdomain.FieldVerificationTxtName, field.TypeString, value)
		_node.VerificationTxtName = value
	}
	if value, ok := _c.mutation.VerificationTxtValue(); ok {
		_spec.SetField(customdomain.FieldVerificationTxtValue, field.TypeString, value)
		_node.VerificationTxtValue = value
	}
	if value, ok := _c.mutation.CnameTarget(); ok {
		_spec.SetField(customdomain.FieldCnameTarget, field.TypeString, value)
		_node.CnameTarget = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(customdomain.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.VerifiedAt(); ok {
		_spec.SetField(customdomain.FieldVerifiedAt, field.TypeTime, value)
		_node.VerifiedAt = &value
	}
	if value, ok := _c.mutation.LastCheckedAt(); ok {
		_spec.SetField(customdomain.FieldLastCheckedAt, field.TypeTime, value)
		_node.LastCheckedAt = &value
	}
	if value, ok := _c.mutation.DisabledAt(); ok {
		_spec.SetField(customdomain.FieldDisabledAt, field.TypeTime, value)
		_node.DisabledAt = &value
	}
	if value, ok := _c.mutation.DisabledReason(); ok {
		_spec.SetField(customdomain.FieldDisabledReason, field.TypeString, value)
		_node.DisabledReason = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customdomain.UserTable,
			Columns: []string{customdomain.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AuthorizedUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   customdomain.AuthorizedUsersTable,
			Columns: customdomain.AuthorizedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &CustomDomainUserCreate{config: _c.config, mutation: newCustomDomainUserMutation(_c.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomDomain.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomDomainUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomDomainCreate) OnConflict(opts ...sql.ConflictOption) *CustomDomainUpsertOne {
	_c.conflict = opts
	return &CustomDomainUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomDomain.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomDomainCreate) OnConflictColumns(columns ...string) *CustomDomainUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomDomainUpsertOne{
		create: _c,
	}
}

type (
	// CustomDomainUpsertOne is the builder for "upsert"-ing
	//  one CustomDomain node.
	CustomDomainUpsertOne struct {
		create *CustomDomainCreate
	}

	// CustomDomainUpsert is the "OnConflict" setter.
	CustomDomainUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomDomainUpsert) SetUpdatedAt(v time.Time) *CustomDomainUpsert {
	u.Set(customdomain.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomDomainUpsert) UpdateUpdatedAt() *CustomDomainUpsert {
	u.SetExcluded(customdomain.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CustomDomainUpsert) SetDeletedAt(v time.Time) *CustomDomainUpsert {
	u.Set(customdomain.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CustomDomainUpsert) UpdateDeletedAt() *CustomDomainUpsert {
	u.SetExcluded(customdomain.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CustomDomainUpsert) ClearDeletedAt() *CustomDomainUpsert {
	u.SetNull(customdomain.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *CustomDomainUpsert) SetUserID(v int64) *CustomDomainUpsert {
	u.Set(customdomain.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CustomDomainUpsert) UpdateUserID() *CustomDomainUpsert {
	u.SetExcluded(customdomain.FieldUserID)
	return u
}

// SetAllUsers sets the "all_users" field.
func (u *CustomDomainUpsert) SetAllUsers(v bool) *CustomDomainUpsert {
	u.Set(customdomain.FieldAllUsers, v)
	return u
}

// UpdateAllUsers sets the "all_users" field to the value that was provided on create.
func (u *CustomDomainUpsert) UpdateAllUsers() *CustomDomainUpsert {
	u.SetExcluded(customdomain.FieldAllUsers)
	return u
}

// SetDomain sets the "domain" field.
func (u *CustomDomainUpsert) SetDomain(v string) *CustomDomainUpsert {
	u.Set(customdomain.FieldDomain, v)
	return u
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *CustomDomainUpsert) UpdateDomain() *CustomDomainUpsert {
	u.SetExcluded(customdomain.FieldDomain)
	return u
}

// SetStatus sets the "status" field.
func (u *CustomDomainUpsert) SetStatus(v string) *CustomDomainUpsert {
	u.Set(customdomain.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CustomDomainUpsert) UpdateStatus() *CustomDomainUpsert {
	u.SetExcluded(customdomain.FieldStatus)
	return u
}

// SetVerificationToken sets the "verification_token" field.
func (u *CustomDomainUpsert) SetVerificationToken(v string) *CustomDomainUpsert {
	u.Set(customdomain.FieldVerificationToken, v)
	return u
}

// UpdateVerificationToken sets the "verification_token" field to the value that was provided on create.
func (u *CustomDomainUpsert) UpdateVerificationToken() *CustomDomainUpsert {
	u.SetExcluded(customdomain.FieldVerificationToken)
	return u
}

// SetVerificationTxtName sets the "verification_txt_name" field.
func (u *CustomDomainUpsert) SetVerificationTxtName(v string) *CustomDomainUpsert {
	u.Set(customdomain.FieldVerificationTxtName, v)
	return u
}

// UpdateVerificationTxtName sets the "verification_txt_name" field to the value that was provided on create.
func (u *CustomDomainUpsert) UpdateVerificationTxtName() *CustomDomainUpsert {
	u.SetExcluded(customdomain.FieldVerificationTxtName)
	return u
}

// SetVerificationTxtValue sets the "verification_txt_value" field.
func (u *CustomDomainUpsert) SetVerificationTxtValue(v string) *CustomDomainUpsert {
	u.Set(customdomain.FieldVerificationTxtValue, v)
	return u
}

// UpdateVerificationTxtValue sets the "verification_txt_value" field to the value that was provided on create.
func (u *CustomDomainUpsert) UpdateVerificationTxtValue() *CustomDomainUpsert {
	u.SetExcluded(customdomain.FieldVerificationTxtValue)
	return u
}

// SetCnameTarget sets the "cname_target" field.
func (u *CustomDomainUpsert) SetCnameTarget(v string) *CustomDomainUpsert {
	u.Set(customdomain.FieldCnameTarget, v)
	return u
}

// UpdateCnameTarget sets the "cname_target" field to the value that was provided on create.
func (u *CustomDomainUpsert) UpdateCnameTarget() *CustomDomainUpsert {
	u.SetExcluded(customdomain.FieldCnameTarget)
	return u
}

// ClearCnameTarget clears the value of the "cname_target" field.
func (u *CustomDomainUpsert) ClearCnameTarget() *CustomDomainUpsert {
	u.SetNull(customdomain.FieldCnameTarget)
	return u
}

// SetLastError sets the "last_error" field.
func (u *CustomDomainUpsert) SetLastError(v string) *CustomDomainUpsert {
	u.Set(customdomain.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *CustomDomainUpsert) UpdateLastError() *CustomDomainUpsert {
	u.SetExcluded(customdomain.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *CustomDomainUpsert) ClearLastError() *CustomDomainUpsert {
	u.SetNull(customdomain.FieldLastError)
	return u
}

// SetVerifiedAt sets the "verified_at" field.
func (u *CustomDomainUpsert) SetVerifiedAt(v time.Time) *CustomDomainUpsert {
	u.Set(customdomain.FieldVerifiedAt, v)
	return u
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *CustomDomainUpsert) UpdateVerifiedAt() *CustomDomainUpsert {
	u.SetExcluded(customdomain.FieldVerifiedAt)
	return u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *CustomDomainUpsert) ClearVerifiedAt() *CustomDomainUpsert {
	u.SetNull(customdomain.FieldVerifiedAt)
	return u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *CustomDomainUpsert) SetLastCheckedAt(v time.Time) *CustomDomainUpsert {
	u.Set(customdomain.FieldLastCheckedAt, v)
	return u
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *CustomDomainUpsert) UpdateLastCheckedAt() *CustomDomainUpsert {
	u.SetExcluded(customdomain.FieldLastCheckedAt)
	return u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *CustomDomainUpsert) ClearLastCheckedAt() *CustomDomainUpsert {
	u.SetNull(customdomain.FieldLastCheckedAt)
	return u
}

// SetDisabledAt sets the "disabled_at" field.
func (u *CustomDomainUpsert) SetDisabledAt(v time.Time) *CustomDomainUpsert {
	u.Set(customdomain.FieldDisabledAt, v)
	return u
}

// UpdateDisabledAt sets the "disabled_at" field to the value that was provided on create.
func (u *CustomDomainUpsert) UpdateDisabledAt() *CustomDomainUpsert {
	u.SetExcluded(customdomain.FieldDisabledAt)
	return u
}

// ClearDisabledAt clears the value of the "disabled_at" field.
func (u *CustomDomainUpsert) ClearDisabledAt() *CustomDomainUpsert {
	u.SetNull(customdomain.FieldDisabledAt)
	return u
}

// SetDisabledReason sets the "disabled_reason" field.
func (u *CustomDomainUpsert) SetDisabledReason(v string) *CustomDomainUpsert {
	u.Set(customdomain.FieldDisabledReason, v)
	return u
}

// UpdateDisabledReason sets the "disabled_reason" field to the value that was provided on create.
func (u *CustomDomainUpsert) UpdateDisabledReason() *CustomDomainUpsert {
	u.SetExcluded(customdomain.FieldDisabledReason)
	return u
}

// ClearDisabledReason clears the value of the "disabled_reason" field.
func (u *CustomDomainUpsert) ClearDisabledReason() *CustomDomainUpsert {
	u.SetNull(customdomain.FieldDisabledReason)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CustomDomain.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CustomDomainUpsertOne) UpdateNewValues() *CustomDomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(customdomain.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomDomain.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CustomDomainUpsertOne) Ignore() *CustomDomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomDomainUpsertOne) DoNothing() *CustomDomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomDomainCreate.OnConflict
// documentation for more info.
func (u *CustomDomainUpsertOne) Update(set func(*CustomDomainUpsert)) *CustomDomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomDomainUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomDomainUpsertOne) SetUpdatedAt(v time.Time) *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomDomainUpsertOne) UpdateUpdatedAt() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CustomDomainUpsertOne) SetDeletedAt(v time.Time) *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CustomDomainUpsertOne) UpdateDeletedAt() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CustomDomainUpsertOne) ClearDeletedAt() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *CustomDomainUpsertOne) SetUserID(v int64) *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CustomDomainUpsertOne) UpdateUserID() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateUserID()
	})
}

// SetAllUsers sets the "all_users" field.
func (u *CustomDomainUpsertOne) SetAllUsers(v bool) *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetAllUsers(v)
	})
}

// UpdateAllUsers sets the "all_users" field to the value that was provided on create.
func (u *CustomDomainUpsertOne) UpdateAllUsers() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateAllUsers()
	})
}

// SetDomain sets the "domain" field.
func (u *CustomDomainUpsertOne) SetDomain(v string) *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetDomain(v)
	})
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *CustomDomainUpsertOne) UpdateDomain() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateDomain()
	})
}

// SetStatus sets the "status" field.
func (u *CustomDomainUpsertOne) SetStatus(v string) *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CustomDomainUpsertOne) UpdateStatus() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateStatus()
	})
}

// SetVerificationToken sets the "verification_token" field.
func (u *CustomDomainUpsertOne) SetVerificationToken(v string) *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetVerificationToken(v)
	})
}

// UpdateVerificationToken sets the "verification_token" field to the value that was provided on create.
func (u *CustomDomainUpsertOne) UpdateVerificationToken() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateVerificationToken()
	})
}

// SetVerificationTxtName sets the "verification_txt_name" field.
func (u *CustomDomainUpsertOne) SetVerificationTxtName(v string) *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetVerificationTxtName(v)
	})
}

// UpdateVerificationTxtName sets the "verification_txt_name" field to the value that was provided on create.
func (u *CustomDomainUpsertOne) UpdateVerificationTxtName() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateVerificationTxtName()
	})
}

// SetVerificationTxtValue sets the "verification_txt_value" field.
func (u *CustomDomainUpsertOne) SetVerificationTxtValue(v string) *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetVerificationTxtValue(v)
	})
}

// UpdateVerificationTxtValue sets the "verification_txt_value" field to the value that was provided on create.
func (u *CustomDomainUpsertOne) UpdateVerificationTxtValue() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateVerificationTxtValue()
	})
}

// SetCnameTarget sets the "cname_target" field.
func (u *CustomDomainUpsertOne) SetCnameTarget(v string) *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetCnameTarget(v)
	})
}

// UpdateCnameTarget sets the "cname_target" field to the value that was provided on create.
func (u *CustomDomainUpsertOne) UpdateCnameTarget() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateCnameTarget()
	})
}

// ClearCnameTarget clears the value of the "cname_target" field.
func (u *CustomDomainUpsertOne) ClearCnameTarget() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.ClearCnameTarget()
	})
}

// SetLastError sets the "last_error" field.
func (u *CustomDomainUpsertOne) SetLastError(v string) *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *CustomDomainUpsertOne) UpdateLastError() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *CustomDomainUpsertOne) ClearLastError() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.ClearLastError()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *CustomDomainUpsertOne) SetVerifiedAt(v time.Time) *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *CustomDomainUpsertOne) UpdateVerifiedAt() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateVerifiedAt()
	})
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *CustomDomainUpsertOne) ClearVerifiedAt() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.ClearVerifiedAt()
	})
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *CustomDomainUpsertOne) SetLastCheckedAt(v time.Time) *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetLastCheckedAt(v)
	})
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *CustomDomainUpsertOne) UpdateLastCheckedAt() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateLastCheckedAt()
	})
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *CustomDomainUpsertOne) ClearLastCheckedAt() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.ClearLastCheckedAt()
	})
}

// SetDisabledAt sets the "disabled_at" field.
func (u *CustomDomainUpsertOne) SetDisabledAt(v time.Time) *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetDisabledAt(v)
	})
}

// UpdateDisabledAt sets the "disabled_at" field to the value that was provided on create.
func (u *CustomDomainUpsertOne) UpdateDisabledAt() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateDisabledAt()
	})
}

// ClearDisabledAt clears the value of the "disabled_at" field.
func (u *CustomDomainUpsertOne) ClearDisabledAt() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.ClearDisabledAt()
	})
}

// SetDisabledReason sets the "disabled_reason" field.
func (u *CustomDomainUpsertOne) SetDisabledReason(v string) *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetDisabledReason(v)
	})
}

// UpdateDisabledReason sets the "disabled_reason" field to the value that was provided on create.
func (u *CustomDomainUpsertOne) UpdateDisabledReason() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateDisabledReason()
	})
}

// ClearDisabledReason clears the value of the "disabled_reason" field.
func (u *CustomDomainUpsertOne) ClearDisabledReason() *CustomDomainUpsertOne {
	return u.Update(func(s *CustomDomainUpsert) {
		s.ClearDisabledReason()
	})
}

// Exec executes the query.
func (u *CustomDomainUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomDomainCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomDomainUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CustomDomainUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CustomDomainUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CustomDomainCreateBulk is the builder for creating many CustomDomain entities in bulk.
type CustomDomainCreateBulk struct {
	config
	err      error
	builders []*CustomDomainCreate
	conflict []sql.ConflictOption
}

// Save creates the CustomDomain entities in the database.
func (_c *CustomDomainCreateBulk) Save(ctx context.Context) ([]*CustomDomain, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CustomDomain, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomDomainMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CustomDomainCreateBulk) SaveX(ctx context.Context) []*CustomDomain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomDomainCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomDomainCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomDomain.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomDomainUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomDomainCreateBulk) OnConflict(opts ...sql.ConflictOption) *CustomDomainUpsertBulk {
	_c.conflict = opts
	return &CustomDomainUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomDomain.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomDomainCreateBulk) OnConflictColumns(columns ...string) *CustomDomainUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomDomainUpsertBulk{
		create: _c,
	}
}

// CustomDomainUpsertBulk is the builder for "upsert"-ing
// a bulk of CustomDomain nodes.
type CustomDomainUpsertBulk struct {
	create *CustomDomainCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CustomDomain.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CustomDomainUpsertBulk) UpdateNewValues() *CustomDomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(customdomain.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomDomain.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CustomDomainUpsertBulk) Ignore() *CustomDomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomDomainUpsertBulk) DoNothing() *CustomDomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomDomainCreateBulk.OnConflict
// documentation for more info.
func (u *CustomDomainUpsertBulk) Update(set func(*CustomDomainUpsert)) *CustomDomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomDomainUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CustomDomainUpsertBulk) SetUpdatedAt(v time.Time) *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CustomDomainUpsertBulk) UpdateUpdatedAt() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *CustomDomainUpsertBulk) SetDeletedAt(v time.Time) *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *CustomDomainUpsertBulk) UpdateDeletedAt() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *CustomDomainUpsertBulk) ClearDeletedAt() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *CustomDomainUpsertBulk) SetUserID(v int64) *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CustomDomainUpsertBulk) UpdateUserID() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateUserID()
	})
}

// SetAllUsers sets the "all_users" field.
func (u *CustomDomainUpsertBulk) SetAllUsers(v bool) *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetAllUsers(v)
	})
}

// UpdateAllUsers sets the "all_users" field to the value that was provided on create.
func (u *CustomDomainUpsertBulk) UpdateAllUsers() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateAllUsers()
	})
}

// SetDomain sets the "domain" field.
func (u *CustomDomainUpsertBulk) SetDomain(v string) *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetDomain(v)
	})
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *CustomDomainUpsertBulk) UpdateDomain() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateDomain()
	})
}

// SetStatus sets the "status" field.
func (u *CustomDomainUpsertBulk) SetStatus(v string) *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *CustomDomainUpsertBulk) UpdateStatus() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateStatus()
	})
}

// SetVerificationToken sets the "verification_token" field.
func (u *CustomDomainUpsertBulk) SetVerificationToken(v string) *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetVerificationToken(v)
	})
}

// UpdateVerificationToken sets the "verification_token" field to the value that was provided on create.
func (u *CustomDomainUpsertBulk) UpdateVerificationToken() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateVerificationToken()
	})
}

// SetVerificationTxtName sets the "verification_txt_name" field.
func (u *CustomDomainUpsertBulk) SetVerificationTxtName(v string) *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetVerificationTxtName(v)
	})
}

// UpdateVerificationTxtName sets the "verification_txt_name" field to the value that was provided on create.
func (u *CustomDomainUpsertBulk) UpdateVerificationTxtName() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateVerificationTxtName()
	})
}

// SetVerificationTxtValue sets the "verification_txt_value" field.
func (u *CustomDomainUpsertBulk) SetVerificationTxtValue(v string) *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetVerificationTxtValue(v)
	})
}

// UpdateVerificationTxtValue sets the "verification_txt_value" field to the value that was provided on create.
func (u *CustomDomainUpsertBulk) UpdateVerificationTxtValue() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateVerificationTxtValue()
	})
}

// SetCnameTarget sets the "cname_target" field.
func (u *CustomDomainUpsertBulk) SetCnameTarget(v string) *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetCnameTarget(v)
	})
}

// UpdateCnameTarget sets the "cname_target" field to the value that was provided on create.
func (u *CustomDomainUpsertBulk) UpdateCnameTarget() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateCnameTarget()
	})
}

// ClearCnameTarget clears the value of the "cname_target" field.
func (u *CustomDomainUpsertBulk) ClearCnameTarget() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.ClearCnameTarget()
	})
}

// SetLastError sets the "last_error" field.
func (u *CustomDomainUpsertBulk) SetLastError(v string) *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *CustomDomainUpsertBulk) UpdateLastError() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *CustomDomainUpsertBulk) ClearLastError() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.ClearLastError()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *CustomDomainUpsertBulk) SetVerifiedAt(v time.Time) *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *CustomDomainUpsertBulk) UpdateVerifiedAt() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateVerifiedAt()
	})
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (u *CustomDomainUpsertBulk) ClearVerifiedAt() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.ClearVerifiedAt()
	})
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *CustomDomainUpsertBulk) SetLastCheckedAt(v time.Time) *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetLastCheckedAt(v)
	})
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *CustomDomainUpsertBulk) UpdateLastCheckedAt() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateLastCheckedAt()
	})
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *CustomDomainUpsertBulk) ClearLastCheckedAt() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.ClearLastCheckedAt()
	})
}

// SetDisabledAt sets the "disabled_at" field.
func (u *CustomDomainUpsertBulk) SetDisabledAt(v time.Time) *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetDisabledAt(v)
	})
}

// UpdateDisabledAt sets the "disabled_at" field to the value that was provided on create.
func (u *CustomDomainUpsertBulk) UpdateDisabledAt() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateDisabledAt()
	})
}

// ClearDisabledAt clears the value of the "disabled_at" field.
func (u *CustomDomainUpsertBulk) ClearDisabledAt() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.ClearDisabledAt()
	})
}

// SetDisabledReason sets the "disabled_reason" field.
func (u *CustomDomainUpsertBulk) SetDisabledReason(v string) *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.SetDisabledReason(v)
	})
}

// UpdateDisabledReason sets the "disabled_reason" field to the value that was provided on create.
func (u *CustomDomainUpsertBulk) UpdateDisabledReason() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.UpdateDisabledReason()
	})
}

// ClearDisabledReason clears the value of the "disabled_reason" field.
func (u *CustomDomainUpsertBulk) ClearDisabledReason() *CustomDomainUpsertBulk {
	return u.Update(func(s *CustomDomainUpsert) {
		s.ClearDisabledReason()
	})
}

// Exec executes the query.
func (u *CustomDomainUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CustomDomainCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomDomainCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomDomainUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
