// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/customdomain"
	"github.com/Wei-Shaw/sub2api/ent/customdomainuser"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CustomDomainUserUpdate is the builder for updating CustomDomainUser entities.
type CustomDomainUserUpdate struct {
	config
	hooks    []Hook
	mutation *CustomDomainUserMutation
}

// Where appends a list predicates to the CustomDomainUserUpdate builder.
func (_u *CustomDomainUserUpdate) Where(ps ...predicate.CustomDomainUser) *CustomDomainUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCustomDomainID sets the "custom_domain_id" field.
func (_u *CustomDomainUserUpdate) SetCustomDomainID(v int64) *CustomDomainUserUpdate {
	_u.mutation.SetCustomDomainID(v)
	return _u
}

// SetNillableCustomDomainID sets the "custom_domain_id" field if the given value is not nil.
func (_u *CustomDomainUserUpdate) SetNillableCustomDomainID(v *int64) *CustomDomainUserUpdate {
	if v != nil {
		_u.SetCustomDomainID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CustomDomainUserUpdate) SetUserID(v int64) *CustomDomainUserUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CustomDomainUserUpdate) SetNillableUserID(v *int64) *CustomDomainUserUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCustomDomain sets the "custom_domain" edge to the CustomDomain entity.
func (_u *CustomDomainUserUpdate) SetCustomDomain(v *CustomDomain) *CustomDomainUserUpdate {
	return _u.SetCustomDomainID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *CustomDomainUserUpdate) SetUser(v *User) *CustomDomainUserUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CustomDomainUserMutation object of the builder.
func (_u *CustomDomainUserUpdate) Mutation() *CustomDomainUserMutation {
	return _u.mutation
}

// ClearCustomDomain clears the "custom_domain" edge to the CustomDomain entity.
func (_u *CustomDomainUserUpdate) ClearCustomDomain() *CustomDomainUserUpdate {
	_u.mutation.ClearCustomDomain()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CustomDomainUserUpdate) ClearUser() *CustomDomainUserUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CustomDomainUserUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomDomainUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CustomDomainUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomDomainUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomDomainUserUpdate) check() error {
	if _u.mutation.CustomDomainCleared() && len(_u.mutation.CustomDomainIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CustomDomainUser.custom_domain"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CustomDomainUser.user"`)
	}
	return nil
}

func (_u *CustomDomainUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(customdomainuser.Table, customdomainuser.Columns, sqlgraph.NewFieldSpec(customdomainuser.FieldCustomDomainID, field.TypeInt64), sqlgraph.NewFieldSpec(customdomainuser.FieldUserID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CustomDomainCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   customdomainuser.CustomDomainTable,
			Columns: []string{customdomainuser.CustomDomainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customdomain.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomDomainIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   customdomainuser.CustomDomainTable,
			Columns: []string{customdomainuser.CustomDomainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customdomain.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   customdomainuser.UserTable,
			Columns: []string{customdomainuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   customdomainuser.UserTable,
			Columns: []string{customdomainuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customdomainuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CustomDomainUserUpdateOne is the builder for updating a single CustomDomainUser entity.
type CustomDomainUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CustomDomainUserMutation
}

// SetCustomDomainID sets the "custom_domain_id" field.
func (_u *CustomDomainUserUpdateOne) SetCustomDomainID(v int64) *CustomDomainUserUpdateOne {
	_u.mutation.SetCustomDomainID(v)
	return _u
}

// SetNillableCustomDomainID sets the "custom_domain_id" field if the given value is not nil.
func (_u *CustomDomainUserUpdateOne) SetNillableCustomDomainID(v *int64) *CustomDomainUserUpdateOne {
	if v != nil {
		_u.SetCustomDomainID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CustomDomainUserUpdateOne) SetUserID(v int64) *CustomDomainUserUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CustomDomainUserUpdateOne) SetNillableUserID(v *int64) *CustomDomainUserUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCustomDomain sets the "custom_domain" edge to the CustomDomain entity.
func (_u *CustomDomainUserUpdateOne) SetCustomDomain(v *CustomDomain) *CustomDomainUserUpdateOne {
	return _u.SetCustomDomainID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *CustomDomainUserUpdateOne) SetUser(v *User) *CustomDomainUserUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the CustomDomainUserMutation object of the builder.
func (_u *CustomDomainUserUpdateOne) Mutation() *CustomDomainUserMutation {
	return _u.mutation
}

// ClearCustomDomain clears the "custom_domain" edge to the CustomDomain entity.
func (_u *CustomDomainUserUpdateOne) ClearCustomDomain() *CustomDomainUserUpdateOne {
	_u.mutation.ClearCustomDomain()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CustomDomainUserUpdateOne) ClearUser() *CustomDomainUserUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the CustomDomainUserUpdate builder.
func (_u *CustomDomainUserUpdateOne) Where(ps ...predicate.CustomDomainUser) *CustomDomainUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CustomDomainUserUpdateOne) Select(field string, fields ...string) *CustomDomainUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CustomDomainUser entity.
func (_u *CustomDomainUserUpdateOne) Save(ctx context.Context) (*CustomDomainUser, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomDomainUserUpdateOne) SaveX(ctx context.Context) *CustomDomainUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CustomDomainUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomDomainUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomDomainUserUpdateOne) check() error {
	if _u.mutation.CustomDomainCleared() && len(_u.mutation.CustomDomainIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CustomDomainUser.custom_domain"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CustomDomainUser.user"`)
	}
	return nil
}

func (_u *CustomDomainUserUpdateOne) sqlSave(ctx context.Context) (_node *CustomDomainUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(customdomainuser.Table, customdomainuser.Columns, sqlgraph.NewFieldSpec(customdomainuser.FieldCustomDomainID, field.TypeInt64), sqlgraph.NewFieldSpec(customdomainuser.FieldUserID, field.TypeInt64))
	if id, ok := _u.mutation.CustomDomainID(); !ok {
		return nil, &ValidationError{Name: "custom_domain_id", err: errors.New(`ent: missing "CustomDomainUser.custom_domain_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.UserID(); !ok {
		return nil, &ValidationError{Name: "user_id", err: errors.New(`ent: missing "CustomDomainUser.user_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !customdomainuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CustomDomainCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   customdomainuser.CustomDomainTable,
			Columns: []string{customdomainuser.CustomDomainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customdomain.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomDomainIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   customdomainuser.CustomDomainTable,
			Columns: []string{customdomainuser.CustomDomainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customdomain.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   customdomainuser.UserTable,
			Columns: []string{customdomainuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   customdomainuser.UserTable,
			Columns: []string{customdomainuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CustomDomainUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customdomainuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
