// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/customdomain"
	"github.com/Wei-Shaw/sub2api/ent/customdomainuser"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CustomDomainUserCreate is the builder for creating a CustomDomainUser entity.
type CustomDomainUserCreate struct {
	config
	mutation *CustomDomainUserMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCustomDomainID sets the "custom_domain_id" field.
func (_c *CustomDomainUserCreate) SetCustomDomainID(v int64) *CustomDomainUserCreate {
	_c.mutation.SetCustomDomainID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *CustomDomainUserCreate) SetUserID(v int64) *CustomDomainUserCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CustomDomainUserCreate) SetCreatedAt(v time.Time) *CustomDomainUserCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CustomDomainUserCreate) SetNillableCreatedAt(v *time.Time) *CustomDomainUserCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCustomDomain sets the "custom_domain" edge to the CustomDomain entity.
func (_c *CustomDomainUserCreate) SetCustomDomain(v *CustomDomain) *CustomDomainUserCreate {
	return _c.SetCustomDomainID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *CustomDomainUserCreate) SetUser(v *User) *CustomDomainUserCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the CustomDomainUserMutation object of the builder.
func (_c *CustomDomainUserCreate) Mutation() *CustomDomainUserMutation {
	return _c.mutation
}

// Save creates the CustomDomainUser in the database.
func (_c *CustomDomainUserCreate) Save(ctx context.Context) (*CustomDomainUser, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CustomDomainUserCreate) SaveX(ctx context.Context) *CustomDomainUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomDomainUserCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomDomainUserCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CustomDomainUserCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := customdomainuser.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CustomDomainUserCreate) check() error {
	if _, ok := _c.mutation.CustomDomainID(); !ok {
		return &ValidationError{Name: "custom_domain_id", err: errors.New(`ent: missing required field "CustomDomainUser.custom_domain_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "CustomDomainUser.user_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "CustomDomainUser.created_at"`)}
	}
	if len(_c.mutation.CustomDomainIDs()) == 0 {
		return &ValidationError{Name: "custom_domain", err: errors.New(`ent: missing required edge "CustomDomainUser.custom_domain"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "CustomDomainUser.user"`)}
	}
	return nil
}

func (_c *CustomDomainUserCreate) sqlSave(ctx context.Context) (*CustomDomainUser, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}

func (_c *CustomDomainUserCreate) createSpec() (*CustomDomainUser, *sqlgraph.CreateSpec) {
	var (
		_node = &CustomDomainUser{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(customdomainuser.Table, nil)
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(customdomainuser.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.CustomDomainIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   customdomainuser.CustomDomainTable,
			Columns: []string{customdomainuser.CustomDomainColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customdomain.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CustomDomainID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   customdomainuser.UserTable,
			Columns: []string{customdomainuser.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomDomainUser.Create().
//		SetCustomDomainID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomDomainUserUpsert) {
//			SetCustomDomainID(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomDomainUserCreate) OnConflict(opts ...sql.ConflictOption) *CustomDomainUserUpsertOne {
	_c.conflict = opts
	return &CustomDomainUserUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomDomainUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomDomainUserCreate) OnConflictColumns(columns ...string) *CustomDomainUserUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomDomainUserUpsertOne{
		create: _c,
	}
}

type (
	// CustomDomainUserUpsertOne is the builder for "upsert"-ing
	//  one CustomDomainUser node.
	CustomDomainUserUpsertOne struct {
		create *CustomDomainUserCreate
	}

	// CustomDomainUserUpsert is the "OnConflict" setter.
	CustomDomainUserUpsert struct {
		*sql.UpdateSet
	}
)

// SetCustomDomainID sets the "custom_domain_id" field.
func (u *CustomDomainUserUpsert) SetCustomDomainID(v int64) *CustomDomainUserUpsert {
	u.Set(customdomainuser.FieldCustomDomainID, v)
	return u
}

// UpdateCustomDomainID sets the "custom_domain_id" field to the value that was provided on create.
func (u *CustomDomainUserUpsert) UpdateCustomDomainID() *CustomDomainUserUpsert {
	u.SetExcluded(customdomainuser.FieldCustomDomainID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *CustomDomainUserUpsert) SetUserID(v int64) *CustomDomainUserUpsert {
	u.Set(customdomainuser.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CustomDomainUserUpsert) UpdateUserID() *CustomDomainUserUpsert {
	u.SetExcluded(customdomainuser.FieldUserID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.CustomDomainUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CustomDomainUserUpsertOne) UpdateNewValues() *CustomDomainUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(customdomainuser.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomDomainUser.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CustomDomainUserUpsertOne) Ignore() *CustomDomainUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomDomainUserUpsertOne) DoNothing() *CustomDomainUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomDomainUserCreate.OnConflict
// documentation for more info.
func (u *CustomDomainUserUpsertOne) Update(set func(*CustomDomainUserUpsert)) *CustomDomainUserUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomDomainUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetCustomDomainID sets the "custom_domain_id" field.
func (u *CustomDomainUserUpsertOne) SetCustomDomainID(v int64) *CustomDomainUserUpsertOne {
	return u.Update(func(s *CustomDomainUserUpsert) {
		s.SetCustomDomainID(v)
	})
}

// UpdateCustomDomainID sets the "custom_domain_id" field to the value that was provided on create.
func (u *CustomDomainUserUpsertOne) UpdateCustomDomainID() *CustomDomainUserUpsertOne {
	return u.Update(func(s *CustomDomainUserUpsert) {
		s.UpdateCustomDomainID()
	})
}

// SetUserID sets the "user_id" field.
func (u *CustomDomainUserUpsertOne) SetUserID(v int64) *CustomDomainUserUpsertOne {
	return u.Update(func(s *CustomDomainUserUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CustomDomainUserUpsertOne) UpdateUserID() *CustomDomainUserUpsertOne {
	return u.Update(func(s *CustomDomainUserUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *CustomDomainUserUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomDomainUserCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomDomainUserUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// CustomDomainUserCreateBulk is the builder for creating many CustomDomainUser entities in bulk.
type CustomDomainUserCreateBulk struct {
	config
	err      error
	builders []*CustomDomainUserCreate
	conflict []sql.ConflictOption
}

// Save creates the CustomDomainUser entities in the database.
func (_c *CustomDomainUserCreateBulk) Save(ctx context.Context) ([]*CustomDomainUser, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CustomDomainUser, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomDomainUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CustomDomainUserCreateBulk) SaveX(ctx context.Context) []*CustomDomainUser {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomDomainUserCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomDomainUserCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.CustomDomainUser.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CustomDomainUserUpsert) {
//			SetCustomDomainID(v+v).
//		}).
//		Exec(ctx)
func (_c *CustomDomainUserCreateBulk) OnConflict(opts ...sql.ConflictOption) *CustomDomainUserUpsertBulk {
	_c.conflict = opts
	return &CustomDomainUserUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.CustomDomainUser.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CustomDomainUserCreateBulk) OnConflictColumns(columns ...string) *CustomDomainUserUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CustomDomainUserUpsertBulk{
		create: _c,
	}
}

// CustomDomainUserUpsertBulk is the builder for "upsert"-ing
// a bulk of CustomDomainUser nodes.
type CustomDomainUserUpsertBulk struct {
	create *CustomDomainUserCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.CustomDomainUser.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *CustomDomainUserUpsertBulk) UpdateNewValues() *CustomDomainUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(customdomainuser.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.CustomDomainUser.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CustomDomainUserUpsertBulk) Ignore() *CustomDomainUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CustomDomainUserUpsertBulk) DoNothing() *CustomDomainUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CustomDomainUserCreateBulk.OnConflict
// documentation for more info.
func (u *CustomDomainUserUpsertBulk) Update(set func(*CustomDomainUserUpsert)) *CustomDomainUserUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CustomDomainUserUpsert{UpdateSet: update})
	}))
	return u
}

// SetCustomDomainID sets the "custom_domain_id" field.
func (u *CustomDomainUserUpsertBulk) SetCustomDomainID(v int64) *CustomDomainUserUpsertBulk {
	return u.Update(func(s *CustomDomainUserUpsert) {
		s.SetCustomDomainID(v)
	})
}

// UpdateCustomDomainID sets the "custom_domain_id" field to the value that was provided on create.
func (u *CustomDomainUserUpsertBulk) UpdateCustomDomainID() *CustomDomainUserUpsertBulk {
	return u.Update(func(s *CustomDomainUserUpsert) {
		s.UpdateCustomDomainID()
	})
}

// SetUserID sets the "user_id" field.
func (u *CustomDomainUserUpsertBulk) SetUserID(v int64) *CustomDomainUserUpsertBulk {
	return u.Update(func(s *CustomDomainUserUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *CustomDomainUserUpsertBulk) UpdateUserID() *CustomDomainUserUpsertBulk {
	return u.Update(func(s *CustomDomainUserUpsert) {
		s.UpdateUserID()
	})
}

// Exec executes the query.
func (u *CustomDomainUserUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CustomDomainUserCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CustomDomainUserCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CustomDomainUserUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
