// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/customdomainuser"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// CustomDomainUserDelete is the builder for deleting a CustomDomainUser entity.
type CustomDomainUserDelete struct {
	config
	hooks    []Hook
	mutation *CustomDomainUserMutation
}

// Where appends a list predicates to the CustomDomainUserDelete builder.
func (_d *CustomDomainUserDelete) Where(ps ...predicate.CustomDomainUser) *CustomDomainUserDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CustomDomainUserDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CustomDomainUserDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CustomDomainUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(customdomainuser.Table, nil)
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CustomDomainUserDeleteOne is the builder for deleting a single CustomDomainUser entity.
type CustomDomainUserDeleteOne struct {
	_d *CustomDomainUserDelete
}

// Where appends a list predicates to the CustomDomainUserDelete builder.
func (_d *CustomDomainUserDeleteOne) Where(ps ...predicate.CustomDomainUser) *CustomDomainUserDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CustomDomainUserDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{customdomainuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CustomDomainUserDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
