// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/customdomain"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CustomDomain is the model entity for the CustomDomain schema.
type CustomDomain struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// AllUsers holds the value of the "all_users" field.
	AllUsers bool `json:"all_users,omitempty"`
	// Domain holds the value of the "domain" field.
	Domain string `json:"domain,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// VerificationToken holds the value of the "verification_token" field.
	VerificationToken string `json:"verification_token,omitempty"`
	// VerificationTxtName holds the value of the "verification_txt_name" field.
	VerificationTxtName string `json:"verification_txt_name,omitempty"`
	// VerificationTxtValue holds the value of the "verification_txt_value" field.
	VerificationTxtValue string `json:"verification_txt_value,omitempty"`
	// CnameTarget holds the value of the "cname_target" field.
	CnameTarget *string `json:"cname_target,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// VerifiedAt holds the value of the "verified_at" field.
	VerifiedAt *time.Time `json:"verified_at,omitempty"`
	// LastCheckedAt holds the value of the "last_checked_at" field.
	LastCheckedAt *time.Time `json:"last_checked_at,omitempty"`
	// DisabledAt holds the value of the "disabled_at" field.
	DisabledAt *time.Time `json:"disabled_at,omitempty"`
	// DisabledReason holds the value of the "disabled_reason" field.
	DisabledReason *string `json:"disabled_reason,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CustomDomainQuery when eager-loading is set.
	Edges        CustomDomainEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CustomDomainEdges holds the relations/edges for other nodes in the graph.
type CustomDomainEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// AuthorizedUsers holds the value of the authorized_users edge.
	AuthorizedUsers []*User `json:"authorized_users,omitempty"`
	// CustomDomainUsers holds the value of the custom_domain_users edge.
	CustomDomainUsers []*CustomDomainUser `json:"custom_domain_users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CustomDomainEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// AuthorizedUsersOrErr returns the AuthorizedUsers value or an error if the edge
// was not loaded in eager-loading.
func (e CustomDomainEdges) AuthorizedUsersOrErr() ([]*User, error) {
	if e.loadedTypes[1] {
		return e.AuthorizedUsers, nil
	}
	return nil, &NotLoadedError{edge: "authorized_users"}
}

// CustomDomainUsersOrErr returns the CustomDomainUsers value or an error if the edge
// was not loaded in eager-loading.
func (e CustomDomainEdges) CustomDomainUsersOrErr() ([]*CustomDomainUser, error) {
	if e.loadedTypes[2] {
		return e.CustomDomainUsers, nil
	}
	return nil, &NotLoadedError{edge: "custom_domain_users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CustomDomain) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case customdomain.FieldAllUsers:
			values[i] = new(sql.NullBool)
		case customdomain.FieldID, customdomain.FieldUserID:
			values[i] = new(sql.NullInt64)
		case customdomain.FieldDomain, customdomain.FieldStatus, customdomain.FieldVerificationToken, customdomain.FieldVerificationTxtName, customdomain.FieldVerificationTxtValue, customdomain.FieldCnameTarget, customdomain.FieldLastError, customdomain.FieldDisabledReason:
			values[i] = new(sql.NullString)
		case customdomain.FieldCreatedAt, customdomain.FieldUpdatedAt, customdomain.FieldDeletedAt, customdomain.FieldVerifiedAt, customdomain.FieldLastCheckedAt, customdomain.FieldDisabledAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CustomDomain fields.
func (_m *CustomDomain) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case customdomain.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case customdomain.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case customdomain.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case customdomain.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case customdomain.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case customdomain.FieldAllUsers:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field all_users", values[i])
			} else if value.Valid {
				_m.AllUsers = value.Bool
			}
		case customdomain.FieldDomain:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field domain", values[i])
			} else if value.Valid {
				_m.Domain = value.String
			}
		case customdomain.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case customdomain.FieldVerificationToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field verification_token", values[i])
			} else if value.Valid {
				_m.VerificationToken = value.String
			}
		case customdomain.FieldVerificationTxtName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field verification_txt_name", values[i])
			} else if value.Valid {
				_m.VerificationTxtName = value.String
			}
		case customdomain.FieldVerificationTxtValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field verification_txt_value", values[i])
			} else if value.Valid {
				_m.VerificationTxtValue = value.String
			}
		case customdomain.FieldCnameTarget:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cname_target", values[i])
			} else if value.Valid {
				_m.CnameTarget = new(string)
				*_m.CnameTarget = value.String
			}
		case customdomain.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case customdomain.FieldVerifiedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field verified_at", values[i])
			} else if value.Valid {
				_m.VerifiedAt = new(time.Time)
				*_m.VerifiedAt = value.Time
			}
		case customdomain.FieldLastCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_checked_at", values[i])
			} else if value.Valid {
				_m.LastCheckedAt = new(time.Time)
				*_m.LastCheckedAt = value.Time
			}
		case customdomain.FieldDisabledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field disabled_at", values[i])
			} else if value.Valid {
				_m.DisabledAt = new(time.Time)
				*_m.DisabledAt = value.Time
			}
		case customdomain.FieldDisabledReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field disabled_reason", values[i])
			} else if value.Valid {
				_m.DisabledReason = new(string)
				*_m.DisabledReason = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CustomDomain.
// This includes values selected through modifiers, order, etc.
func (_m *CustomDomain) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the CustomDomain entity.
func (_m *CustomDomain) QueryUser() *UserQuery {
	return NewCustomDomainClient(_m.config).QueryUser(_m)
}

// QueryAuthorizedUsers queries the "authorized_users" edge of the CustomDomain entity.
func (_m *CustomDomain) QueryAuthorizedUsers() *UserQuery {
	return NewCustomDomainClient(_m.config).QueryAuthorizedUsers(_m)
}

// QueryCustomDomainUsers queries the "custom_domain_users" edge of the CustomDomain entity.
func (_m *CustomDomain) QueryCustomDomainUsers() *CustomDomainUserQuery {
	return NewCustomDomainClient(_m.config).QueryCustomDomainUsers(_m)
}

// Update returns a builder for updating this CustomDomain.
// Note that you need to call CustomDomain.Unwrap() before calling this method if this CustomDomain
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CustomDomain) Update() *CustomDomainUpdateOne {
	return NewCustomDomainClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CustomDomain entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CustomDomain) Unwrap() *CustomDomain {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CustomDomain is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CustomDomain) String() string {
	var builder strings.Builder
	builder.WriteString("CustomDomain(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("all_users=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllUsers))
	builder.WriteString(", ")
	builder.WriteString("domain=")
	builder.WriteString(_m.Domain)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("verification_token=")
	builder.WriteString(_m.VerificationToken)
	builder.WriteString(", ")
	builder.WriteString("verification_txt_name=")
	builder.WriteString(_m.VerificationTxtName)
	builder.WriteString(", ")
	builder.WriteString("verification_txt_value=")
	builder.WriteString(_m.VerificationTxtValue)
	builder.WriteString(", ")
	if v := _m.CnameTarget; v != nil {
		builder.WriteString("cname_target=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.VerifiedAt; v != nil {
		builder.WriteString("verified_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastCheckedAt; v != nil {
		builder.WriteString("last_checked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DisabledAt; v != nil {
		builder.WriteString("disabled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DisabledReason; v != nil {
		builder.WriteString("disabled_reason=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// CustomDomains is a parsable slice of CustomDomain.
type CustomDomains []*CustomDomain
