// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/customdomain"
	"github.com/Wei-Shaw/sub2api/ent/customdomainuser"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CustomDomainUserQuery is the builder for querying CustomDomainUser entities.
type CustomDomainUserQuery struct {
	config
	ctx              *QueryContext
	order            []customdomainuser.OrderOption
	inters           []Interceptor
	predicates       []predicate.CustomDomainUser
	withCustomDomain *CustomDomainQuery
	withUser         *UserQuery
	modifiers        []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CustomDomainUserQuery builder.
func (_q *CustomDomainUserQuery) Where(ps ...predicate.CustomDomainUser) *CustomDomainUserQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *CustomDomainUserQuery) Limit(limit int) *CustomDomainUserQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *CustomDomainUserQuery) Offset(offset int) *CustomDomainUserQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *CustomDomainUserQuery) Unique(unique bool) *CustomDomainUserQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *CustomDomainUserQuery) Order(o ...customdomainuser.OrderOption) *CustomDomainUserQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryCustomDomain chains the current query on the "custom_domain" edge.
func (_q *CustomDomainUserQuery) QueryCustomDomain() *CustomDomainQuery {
	query := (&CustomDomainClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(customdomainuser.Table, customdomainuser.CustomDomainColumn, selector),
			sqlgraph.To(customdomain.Table, customdomain.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, customdomainuser.CustomDomainTable, customdomainuser.CustomDomainColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (_q *CustomDomainUserQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(customdomainuser.Table, customdomainuser.UserColumn, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, customdomainuser.UserTable, customdomainuser.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first CustomDomainUser entity from the query.
// Returns a *NotFoundError when no CustomDomainUser was found.
func (_q *CustomDomainUserQuery) First(ctx context.Context) (*CustomDomainUser, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{customdomainuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *CustomDomainUserQuery) FirstX(ctx context.Context) *CustomDomainUser {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// Only returns a single CustomDomainUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CustomDomainUser entity is found.
// Returns a *NotFoundError when no CustomDomainUser entities are found.
func (_q *CustomDomainUserQuery) Only(ctx context.Context) (*CustomDomainUser, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{customdomainuser.Label}
	default:
		return nil, &NotSingularError{customdomainuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *CustomDomainUserQuery) OnlyX(ctx context.Context) *CustomDomainUser {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// All executes the query and returns a list of CustomDomainUsers.
func (_q *CustomDomainUserQuery) All(ctx context.Context) ([]*CustomDomainUser, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*CustomDomainUser, *CustomDomainUserQuery]()
	return withInterceptors[[]*CustomDomainUser](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *CustomDomainUserQuery) AllX(ctx context.Context) []*CustomDomainUser {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// Count returns the count of the given query.
func (_q *CustomDomainUserQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*CustomDomainUserQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *CustomDomainUserQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *CustomDomainUserQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.First(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *CustomDomainUserQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CustomDomainUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *CustomDomainUserQuery) Clone() *CustomDomainUserQuery {
	if _q == nil {
		return nil
	}
	return &CustomDomainUserQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]customdomainuser.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.CustomDomainUser{}, _q.predicates...),
		withCustomDomain: _q.withCustomDomain.Clone(),
		withUser:         _q.withUser.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithCustomDomain tells the query-builder to eager-load the nodes that are connected to
// the "custom_domain" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CustomDomainUserQuery) WithCustomDomain(opts ...func(*CustomDomainQuery)) *CustomDomainUserQuery {
	query := (&CustomDomainClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCustomDomain = query
	return _q
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *CustomDomainUserQuery) WithUser(opts ...func(*UserQuery)) *CustomDomainUserQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CustomDomainID int64 `json:"custom_domain_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CustomDomainUser.Query().
//		GroupBy(customdomainuser.FieldCustomDomainID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *CustomDomainUserQuery) GroupBy(field string, fields ...string) *CustomDomainUserGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &CustomDomainUserGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = customdomainuser.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CustomDomainID int64 `json:"custom_domain_id,omitempty"`
//	}
//
//	client.CustomDomainUser.Query().
//		Select(customdomainuser.FieldCustomDomainID).
//		Scan(ctx, &v)
func (_q *CustomDomainUserQuery) Select(fields ...string) *CustomDomainUserSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &CustomDomainUserSelect{CustomDomainUserQuery: _q}
	sbuild.label = customdomainuser.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a CustomDomainUserSelect configured with the given aggregations.
func (_q *CustomDomainUserQuery) Aggregate(fns ...AggregateFunc) *CustomDomainUserSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *CustomDomainUserQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !customdomainuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *CustomDomainUserQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CustomDomainUser, error) {
	var (
		nodes       = []*CustomDomainUser{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withCustomDomain != nil,
			_q.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CustomDomainUser).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CustomDomainUser{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withCustomDomain; query != nil {
		if err := _q.loadCustomDomain(ctx, query, nodes, nil,
			func(n *CustomDomainUser, e *CustomDomain) { n.Edges.CustomDomain = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *CustomDomainUser, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *CustomDomainUserQuery) loadCustomDomain(ctx context.Context, query *CustomDomainQuery, nodes []*CustomDomainUser, init func(*CustomDomainUser), assign func(*CustomDomainUser, *CustomDomain)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CustomDomainUser)
	for i := range nodes {
		fk := nodes[i].CustomDomainID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(customdomain.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "custom_domain_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *CustomDomainUserQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*CustomDomainUser, init func(*CustomDomainUser), assign func(*CustomDomainUser, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*CustomDomainUser)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *CustomDomainUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Unique = false
	_spec.Node.Columns = nil
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *CustomDomainUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(customdomainuser.Table, customdomainuser.Columns, nil)
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		for i := range fields {
			_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
		}
		if _q.withCustomDomain != nil {
			_spec.Node.AddColumnOnce(customdomainuser.FieldCustomDomainID)
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(customdomainuser.FieldUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *CustomDomainUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(customdomainuser.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = customdomainuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *CustomDomainUserQuery) ForUpdate(opts ...sql.LockOption) *CustomDomainUserQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *CustomDomainUserQuery) ForShare(opts ...sql.LockOption) *CustomDomainUserQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// CustomDomainUserGroupBy is the group-by builder for CustomDomainUser entities.
type CustomDomainUserGroupBy struct {
	selector
	build *CustomDomainUserQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *CustomDomainUserGroupBy) Aggregate(fns ...AggregateFunc) *CustomDomainUserGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *CustomDomainUserGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CustomDomainUserQuery, *CustomDomainUserGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *CustomDomainUserGroupBy) sqlScan(ctx context.Context, root *CustomDomainUserQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// CustomDomainUserSelect is the builder for selecting fields of CustomDomainUser entities.
type CustomDomainUserSelect struct {
	*CustomDomainUserQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *CustomDomainUserSelect) Aggregate(fns ...AggregateFunc) *CustomDomainUserSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *CustomDomainUserSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*CustomDomainUserQuery, *CustomDomainUserSelect](ctx, _s.CustomDomainUserQuery, _s, _s.inters, v)
}

func (_s *CustomDomainUserSelect) sqlScan(ctx context.Context, root *CustomDomainUserQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
