// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/customdomain"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// CustomDomainUpdate is the builder for updating CustomDomain entities.
type CustomDomainUpdate struct {
	config
	hooks    []Hook
	mutation *CustomDomainMutation
}

// Where appends a list predicates to the CustomDomainUpdate builder.
func (_u *CustomDomainUpdate) Where(ps ...predicate.CustomDomain) *CustomDomainUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomDomainUpdate) SetUpdatedAt(v time.Time) *CustomDomainUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CustomDomainUpdate) SetDeletedAt(v time.Time) *CustomDomainUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CustomDomainUpdate) SetNillableDeletedAt(v *time.Time) *CustomDomainUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CustomDomainUpdate) ClearDeletedAt() *CustomDomainUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CustomDomainUpdate) SetUserID(v int64) *CustomDomainUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CustomDomainUpdate) SetNillableUserID(v *int64) *CustomDomainUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAllUsers sets the "all_users" field.
func (_u *CustomDomainUpdate) SetAllUsers(v bool) *CustomDomainUpdate {
	_u.mutation.SetAllUsers(v)
	return _u
}

// SetNillableAllUsers sets the "all_users" field if the given value is not nil.
func (_u *CustomDomainUpdate) SetNillableAllUsers(v *bool) *CustomDomainUpdate {
	if v != nil {
		_u.SetAllUsers(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *CustomDomainUpdate) SetDomain(v string) *CustomDomainUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *CustomDomainUpdate) SetNillableDomain(v *string) *CustomDomainUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CustomDomainUpdate) SetStatus(v string) *CustomDomainUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CustomDomainUpdate) SetNillableStatus(v *string) *CustomDomainUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVerificationToken sets the "verification_token" field.
func (_u *CustomDomainUpdate) SetVerificationToken(v string) *CustomDomainUpdate {
	_u.mutation.SetVerificationToken(v)
	return _u
}

// SetNillableVerificationToken sets the "verification_token" field if the given value is not nil.
func (_u *CustomDomainUpdate) SetNillableVerificationToken(v *string) *CustomDomainUpdate {
	if v != nil {
		_u.SetVerificationToken(*v)
	}
	return _u
}

// SetVerificationTxtName sets the "verification_txt_name" field.
func (_u *CustomDomainUpdate) SetVerificationTxtName(v string) *CustomDomainUpdate {
	_u.mutation.SetVerificationTxtName(v)
	return _u
}

// SetNillableVerificationTxtName sets the "verification_txt_name" field if the given value is not nil.
func (_u *CustomDomainUpdate) SetNillableVerificationTxtName(v *string) *CustomDomainUpdate {
	if v != nil {
		_u.SetVerificationTxtName(*v)
	}
	return _u
}

// SetVerificationTxtValue sets the "verification_txt_value" field.
func (_u *CustomDomainUpdate) SetVerificationTxtValue(v string) *CustomDomainUpdate {
	_u.mutation.SetVerificationTxtValue(v)
	return _u
}

// SetNillableVerificationTxtValue sets the "verification_txt_value" field if the given value is not nil.
func (_u *CustomDomainUpdate) SetNillableVerificationTxtValue(v *string) *CustomDomainUpdate {
	if v != nil {
		_u.SetVerificationTxtValue(*v)
	}
	return _u
}

// SetCnameTarget sets the "cname_target" field.
func (_u *CustomDomainUpdate) SetCnameTarget(v string) *CustomDomainUpdate {
	_u.mutation.SetCnameTarget(v)
	return _u
}

// SetNillableCnameTarget sets the "cname_target" field if the given value is not nil.
func (_u *CustomDomainUpdate) SetNillableCnameTarget(v *string) *CustomDomainUpdate {
	if v != nil {
		_u.SetCnameTarget(*v)
	}
	return _u
}

// ClearCnameTarget clears the value of the "cname_target" field.
func (_u *CustomDomainUpdate) ClearCnameTarget() *CustomDomainUpdate {
	_u.mutation.ClearCnameTarget()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *CustomDomainUpdate) SetLastError(v string) *CustomDomainUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *CustomDomainUpdate) SetNillableLastError(v *string) *CustomDomainUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *CustomDomainUpdate) ClearLastError() *CustomDomainUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetVerifiedAt sets the "verified_at" field.
func (_u *CustomDomainUpdate) SetVerifiedAt(v time.Time) *CustomDomainUpdate {
	_u.mutation.SetVerifiedAt(v)
	return _u
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *CustomDomainUpdate) SetNillableVerifiedAt(v *time.Time) *CustomDomainUpdate {
	if v != nil {
		_u.SetVerifiedAt(*v)
	}
	return _u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (_u *CustomDomainUpdate) ClearVerifiedAt() *CustomDomainUpdate {
	_u.mutation.ClearVerifiedAt()
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *CustomDomainUpdate) SetLastCheckedAt(v time.Time) *CustomDomainUpdate {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *CustomDomainUpdate) SetNillableLastCheckedAt(v *time.Time) *CustomDomainUpdate {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *CustomDomainUpdate) ClearLastCheckedAt() *CustomDomainUpdate {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetDisabledAt sets the "disabled_at" field.
func (_u *CustomDomainUpdate) SetDisabledAt(v time.Time) *CustomDomainUpdate {
	_u.mutation.SetDisabledAt(v)
	return _u
}

// SetNillableDisabledAt sets the "disabled_at" field if the given value is not nil.
func (_u *CustomDomainUpdate) SetNillableDisabledAt(v *time.Time) *CustomDomainUpdate {
	if v != nil {
		_u.SetDisabledAt(*v)
	}
	return _u
}

// ClearDisabledAt clears the value of the "disabled_at" field.
func (_u *CustomDomainUpdate) ClearDisabledAt() *CustomDomainUpdate {
	_u.mutation.ClearDisabledAt()
	return _u
}

// SetDisabledReason sets the "disabled_reason" field.
func (_u *CustomDomainUpdate) SetDisabledReason(v string) *CustomDomainUpdate {
	_u.mutation.SetDisabledReason(v)
	return _u
}

// SetNillableDisabledReason sets the "disabled_reason" field if the given value is not nil.
func (_u *CustomDomainUpdate) SetNillableDisabledReason(v *string) *CustomDomainUpdate {
	if v != nil {
		_u.SetDisabledReason(*v)
	}
	return _u
}

// ClearDisabledReason clears the value of the "disabled_reason" field.
func (_u *CustomDomainUpdate) ClearDisabledReason() *CustomDomainUpdate {
	_u.mutation.ClearDisabledReason()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CustomDomainUpdate) SetUser(v *User) *CustomDomainUpdate {
	return _u.SetUserID(v.ID)
}

// AddAuthorizedUserIDs adds the "authorized_users" edge to the User entity by IDs.
func (_u *CustomDomainUpdate) AddAuthorizedUserIDs(ids ...int64) *CustomDomainUpdate {
	_u.mutation.AddAuthorizedUserIDs(ids...)
	return _u
}

// AddAuthorizedUsers adds the "authorized_users" edges to the User entity.
func (_u *CustomDomainUpdate) AddAuthorizedUsers(v ...*User) *CustomDomainUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAuthorizedUserIDs(ids...)
}

// Mutation returns the CustomDomainMutation object of the builder.
func (_u *CustomDomainUpdate) Mutation() *CustomDomainMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CustomDomainUpdate) ClearUser() *CustomDomainUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAuthorizedUsers clears all "authorized_users" edges to the User entity.
func (_u *CustomDomainUpdate) ClearAuthorizedUsers() *CustomDomainUpdate {
	_u.mutation.ClearAuthorizedUsers()
	return _u
}

// RemoveAuthorizedUserIDs removes the "authorized_users" edge to User entities by IDs.
func (_u *CustomDomainUpdate) RemoveAuthorizedUserIDs(ids ...int64) *CustomDomainUpdate {
	_u.mutation.RemoveAuthorizedUserIDs(ids...)
	return _u
}

// RemoveAuthorizedUsers removes "authorized_users" edges to User entities.
func (_u *CustomDomainUpdate) RemoveAuthorizedUsers(v ...*User) *CustomDomainUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAuthorizedUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CustomDomainUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomDomainUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CustomDomainUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomDomainUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomDomainUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if customdomain.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized customdomain.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := customdomain.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomDomainUpdate) check() error {
	if v, ok := _u.mutation.Domain(); ok {
		if err := customdomain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "CustomDomain.domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := customdomain.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CustomDomain.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VerificationToken(); ok {
		if err := customdomain.VerificationTokenValidator(v); err != nil {
			return &ValidationError{Name: "verification_token", err: fmt.Errorf(`ent: validator failed for field "CustomDomain.verification_token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VerificationTxtName(); ok {
		if err := customdomain.VerificationTxtNameValidator(v); err != nil {
			return &ValidationError{Name: "verification_txt_name", err: fmt.Errorf(`ent: validator failed for field "CustomDomain.verification_txt_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VerificationTxtValue(); ok {
		if err := customdomain.VerificationTxtValueValidator(v); err != nil {
			return &ValidationError{Name: "verification_txt_value", err: fmt.Errorf(`ent: validator failed for field "CustomDomain.verification_txt_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CnameTarget(); ok {
		if err := customdomain.CnameTargetValidator(v); err != nil {
			return &ValidationError{Name: "cname_target", err: fmt.Errorf(`ent: validator failed for field "CustomDomain.cname_target": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CustomDomain.user"`)
	}
	return nil
}

func (_u *CustomDomainUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(customdomain.Table, customdomain.Columns, sqlgraph.NewFieldSpec(customdomain.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(customdomain.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(customdomain.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(customdomain.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AllUsers(); ok {
		_spec.SetField(customdomain.FieldAllUsers, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(customdomain.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(customdomain.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerificationToken(); ok {
		_spec.SetField(customdomain.FieldVerificationToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerificationTxtName(); ok {
		_spec.SetField(customdomain.FieldVerificationTxtName, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerificationTxtValue(); ok {
		_spec.SetField(customdomain.FieldVerificationTxtValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.CnameTarget(); ok {
		_spec.SetField(customdomain.FieldCnameTarget, field.TypeString, value)
	}
	if _u.mutation.CnameTargetCleared() {
		_spec.ClearField(customdomain.FieldCnameTarget, field.TypeString)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(customdomain.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(customdomain.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(customdomain.FieldVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.VerifiedAtCleared() {
		_spec.ClearField(customdomain.FieldVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(customdomain.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(customdomain.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DisabledAt(); ok {
		_spec.SetField(customdomain.FieldDisabledAt, field.TypeTime, value)
	}
	if _u.mutation.DisabledAtCleared() {
		_spec.ClearField(customdomain.FieldDisabledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DisabledReason(); ok {
		_spec.SetField(customdomain.FieldDisabledReason, field.TypeString, value)
	}
	if _u.mutation.DisabledReasonCleared() {
		_spec.ClearField(customdomain.FieldDisabledReason, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customdomain.UserTable,
			Columns: []string{customdomain.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customdomain.UserTable,
			Columns: []string{customdomain.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorizedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   customdomain.AuthorizedUsersTable,
			Columns: customdomain.AuthorizedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		createE := &CustomDomainUserCreate{config: _u.config, mutation: newCustomDomainUserMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAuthorizedUsersIDs(); len(nodes) > 0 && !_u.mutation.AuthorizedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   customdomain.AuthorizedUsersTable,
			Columns: customdomain.AuthorizedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &CustomDomainUserCreate{config: _u.config, mutation: newCustomDomainUserMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorizedUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   customdomain.AuthorizedUsersTable,
			Columns: customdomain.AuthorizedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &CustomDomainUserCreate{config: _u.config, mutation: newCustomDomainUserMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customdomain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CustomDomainUpdateOne is the builder for updating a single CustomDomain entity.
type CustomDomainUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CustomDomainMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomDomainUpdateOne) SetUpdatedAt(v time.Time) *CustomDomainUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *CustomDomainUpdateOne) SetDeletedAt(v time.Time) *CustomDomainUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *CustomDomainUpdateOne) SetNillableDeletedAt(v *time.Time) *CustomDomainUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *CustomDomainUpdateOne) ClearDeletedAt() *CustomDomainUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *CustomDomainUpdateOne) SetUserID(v int64) *CustomDomainUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *CustomDomainUpdateOne) SetNillableUserID(v *int64) *CustomDomainUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAllUsers sets the "all_users" field.
func (_u *CustomDomainUpdateOne) SetAllUsers(v bool) *CustomDomainUpdateOne {
	_u.mutation.SetAllUsers(v)
	return _u
}

// SetNillableAllUsers sets the "all_users" field if the given value is not nil.
func (_u *CustomDomainUpdateOne) SetNillableAllUsers(v *bool) *CustomDomainUpdateOne {
	if v != nil {
		_u.SetAllUsers(*v)
	}
	return _u
}

// SetDomain sets the "domain" field.
func (_u *CustomDomainUpdateOne) SetDomain(v string) *CustomDomainUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *CustomDomainUpdateOne) SetNillableDomain(v *string) *CustomDomainUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CustomDomainUpdateOne) SetStatus(v string) *CustomDomainUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CustomDomainUpdateOne) SetNillableStatus(v *string) *CustomDomainUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVerificationToken sets the "verification_token" field.
func (_u *CustomDomainUpdateOne) SetVerificationToken(v string) *CustomDomainUpdateOne {
	_u.mutation.SetVerificationToken(v)
	return _u
}

// SetNillableVerificationToken sets the "verification_token" field if the given value is not nil.
func (_u *CustomDomainUpdateOne) SetNillableVerificationToken(v *string) *CustomDomainUpdateOne {
	if v != nil {
		_u.SetVerificationToken(*v)
	}
	return _u
}

// SetVerificationTxtName sets the "verification_txt_name" field.
func (_u *CustomDomainUpdateOne) SetVerificationTxtName(v string) *CustomDomainUpdateOne {
	_u.mutation.SetVerificationTxtName(v)
	return _u
}

// SetNillableVerificationTxtName sets the "verification_txt_name" field if the given value is not nil.
func (_u *CustomDomainUpdateOne) SetNillableVerificationTxtName(v *string) *CustomDomainUpdateOne {
	if v != nil {
		_u.SetVerificationTxtName(*v)
	}
	return _u
}

// SetVerificationTxtValue sets the "verification_txt_value" field.
func (_u *CustomDomainUpdateOne) SetVerificationTxtValue(v string) *CustomDomainUpdateOne {
	_u.mutation.SetVerificationTxtValue(v)
	return _u
}

// SetNillableVerificationTxtValue sets the "verification_txt_value" field if the given value is not nil.
func (_u *CustomDomainUpdateOne) SetNillableVerificationTxtValue(v *string) *CustomDomainUpdateOne {
	if v != nil {
		_u.SetVerificationTxtValue(*v)
	}
	return _u
}

// SetCnameTarget sets the "cname_target" field.
func (_u *CustomDomainUpdateOne) SetCnameTarget(v string) *CustomDomainUpdateOne {
	_u.mutation.SetCnameTarget(v)
	return _u
}

// SetNillableCnameTarget sets the "cname_target" field if the given value is not nil.
func (_u *CustomDomainUpdateOne) SetNillableCnameTarget(v *string) *CustomDomainUpdateOne {
	if v != nil {
		_u.SetCnameTarget(*v)
	}
	return _u
}

// ClearCnameTarget clears the value of the "cname_target" field.
func (_u *CustomDomainUpdateOne) ClearCnameTarget() *CustomDomainUpdateOne {
	_u.mutation.ClearCnameTarget()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *CustomDomainUpdateOne) SetLastError(v string) *CustomDomainUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *CustomDomainUpdateOne) SetNillableLastError(v *string) *CustomDomainUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *CustomDomainUpdateOne) ClearLastError() *CustomDomainUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetVerifiedAt sets the "verified_at" field.
func (_u *CustomDomainUpdateOne) SetVerifiedAt(v time.Time) *CustomDomainUpdateOne {
	_u.mutation.SetVerifiedAt(v)
	return _u
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *CustomDomainUpdateOne) SetNillableVerifiedAt(v *time.Time) *CustomDomainUpdateOne {
	if v != nil {
		_u.SetVerifiedAt(*v)
	}
	return _u
}

// ClearVerifiedAt clears the value of the "verified_at" field.
func (_u *CustomDomainUpdateOne) ClearVerifiedAt() *CustomDomainUpdateOne {
	_u.mutation.ClearVerifiedAt()
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *CustomDomainUpdateOne) SetLastCheckedAt(v time.Time) *CustomDomainUpdateOne {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *CustomDomainUpdateOne) SetNillableLastCheckedAt(v *time.Time) *CustomDomainUpdateOne {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *CustomDomainUpdateOne) ClearLastCheckedAt() *CustomDomainUpdateOne {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetDisabledAt sets the "disabled_at" field.
func (_u *CustomDomainUpdateOne) SetDisabledAt(v time.Time) *CustomDomainUpdateOne {
	_u.mutation.SetDisabledAt(v)
	return _u
}

// SetNillableDisabledAt sets the "disabled_at" field if the given value is not nil.
func (_u *CustomDomainUpdateOne) SetNillableDisabledAt(v *time.Time) *CustomDomainUpdateOne {
	if v != nil {
		_u.SetDisabledAt(*v)
	}
	return _u
}

// ClearDisabledAt clears the value of the "disabled_at" field.
func (_u *CustomDomainUpdateOne) ClearDisabledAt() *CustomDomainUpdateOne {
	_u.mutation.ClearDisabledAt()
	return _u
}

// SetDisabledReason sets the "disabled_reason" field.
func (_u *CustomDomainUpdateOne) SetDisabledReason(v string) *CustomDomainUpdateOne {
	_u.mutation.SetDisabledReason(v)
	return _u
}

// SetNillableDisabledReason sets the "disabled_reason" field if the given value is not nil.
func (_u *CustomDomainUpdateOne) SetNillableDisabledReason(v *string) *CustomDomainUpdateOne {
	if v != nil {
		_u.SetDisabledReason(*v)
	}
	return _u
}

// ClearDisabledReason clears the value of the "disabled_reason" field.
func (_u *CustomDomainUpdateOne) ClearDisabledReason() *CustomDomainUpdateOne {
	_u.mutation.ClearDisabledReason()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *CustomDomainUpdateOne) SetUser(v *User) *CustomDomainUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddAuthorizedUserIDs adds the "authorized_users" edge to the User entity by IDs.
func (_u *CustomDomainUpdateOne) AddAuthorizedUserIDs(ids ...int64) *CustomDomainUpdateOne {
	_u.mutation.AddAuthorizedUserIDs(ids...)
	return _u
}

// AddAuthorizedUsers adds the "authorized_users" edges to the User entity.
func (_u *CustomDomainUpdateOne) AddAuthorizedUsers(v ...*User) *CustomDomainUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAuthorizedUserIDs(ids...)
}

// Mutation returns the CustomDomainMutation object of the builder.
func (_u *CustomDomainUpdateOne) Mutation() *CustomDomainMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *CustomDomainUpdateOne) ClearUser() *CustomDomainUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAuthorizedUsers clears all "authorized_users" edges to the User entity.
func (_u *CustomDomainUpdateOne) ClearAuthorizedUsers() *CustomDomainUpdateOne {
	_u.mutation.ClearAuthorizedUsers()
	return _u
}

// RemoveAuthorizedUserIDs removes the "authorized_users" edge to User entities by IDs.
func (_u *CustomDomainUpdateOne) RemoveAuthorizedUserIDs(ids ...int64) *CustomDomainUpdateOne {
	_u.mutation.RemoveAuthorizedUserIDs(ids...)
	return _u
}

// RemoveAuthorizedUsers removes "authorized_users" edges to User entities.
func (_u *CustomDomainUpdateOne) RemoveAuthorizedUsers(v ...*User) *CustomDomainUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAuthorizedUserIDs(ids...)
}

// Where appends a list predicates to the CustomDomainUpdate builder.
func (_u *CustomDomainUpdateOne) Where(ps ...predicate.CustomDomain) *CustomDomainUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CustomDomainUpdateOne) Select(field string, fields ...string) *CustomDomainUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CustomDomain entity.
func (_u *CustomDomainUpdateOne) Save(ctx context.Context) (*CustomDomain, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomDomainUpdateOne) SaveX(ctx context.Context) *CustomDomain {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CustomDomainUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomDomainUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CustomDomainUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if customdomain.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized customdomain.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := customdomain.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *CustomDomainUpdateOne) check() error {
	if v, ok := _u.mutation.Domain(); ok {
		if err := customdomain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "CustomDomain.domain": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := customdomain.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "CustomDomain.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VerificationToken(); ok {
		if err := customdomain.VerificationTokenValidator(v); err != nil {
			return &ValidationError{Name: "verification_token", err: fmt.Errorf(`ent: validator failed for field "CustomDomain.verification_token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VerificationTxtName(); ok {
		if err := customdomain.VerificationTxtNameValidator(v); err != nil {
			return &ValidationError{Name: "verification_txt_name", err: fmt.Errorf(`ent: validator failed for field "CustomDomain.verification_txt_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VerificationTxtValue(); ok {
		if err := customdomain.VerificationTxtValueValidator(v); err != nil {
			return &ValidationError{Name: "verification_txt_value", err: fmt.Errorf(`ent: validator failed for field "CustomDomain.verification_txt_value": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CnameTarget(); ok {
		if err := customdomain.CnameTargetValidator(v); err != nil {
			return &ValidationError{Name: "cname_target", err: fmt.Errorf(`ent: validator failed for field "CustomDomain.cname_target": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "CustomDomain.user"`)
	}
	return nil
}

func (_u *CustomDomainUpdateOne) sqlSave(ctx context.Context) (_node *CustomDomain, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(customdomain.Table, customdomain.Columns, sqlgraph.NewFieldSpec(customdomain.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CustomDomain.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, customdomain.FieldID)
		for _, f := range fields {
			if !customdomain.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != customdomain.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(customdomain.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(customdomain.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(customdomain.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AllUsers(); ok {
		_spec.SetField(customdomain.FieldAllUsers, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(customdomain.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(customdomain.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerificationToken(); ok {
		_spec.SetField(customdomain.FieldVerificationToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerificationTxtName(); ok {
		_spec.SetField(customdomain.FieldVerificationTxtName, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerificationTxtValue(); ok {
		_spec.SetField(customdomain.FieldVerificationTxtValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.CnameTarget(); ok {
		_spec.SetField(customdomain.FieldCnameTarget, field.TypeString, value)
	}
	if _u.mutation.CnameTargetCleared() {
		_spec.ClearField(customdomain.FieldCnameTarget, field.TypeString)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(customdomain.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(customdomain.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(customdomain.FieldVerifiedAt, field.TypeTime, value)
	}
	if _u.mutation.VerifiedAtCleared() {
		_spec.ClearField(customdomain.FieldVerifiedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(customdomain.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(customdomain.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DisabledAt(); ok {
		_spec.SetField(customdomain.FieldDisabledAt, field.TypeTime, value)
	}
	if _u.mutation.DisabledAtCleared() {
		_spec.ClearField(customdomain.FieldDisabledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DisabledReason(); ok {
		_spec.SetField(customdomain.FieldDisabledReason, field.TypeString, value)
	}
	if _u.mutation.DisabledReasonCleared() {
		_spec.ClearField(customdomain.FieldDisabledReason, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customdomain.UserTable,
			Columns: []string{customdomain.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customdomain.UserTable,
			Columns: []string{customdomain.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AuthorizedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   customdomain.AuthorizedUsersTable,
			Columns: customdomain.AuthorizedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		createE := &CustomDomainUserCreate{config: _u.config, mutation: newCustomDomainUserMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAuthorizedUsersIDs(); len(nodes) > 0 && !_u.mutation.AuthorizedUsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   customdomain.AuthorizedUsersTable,
			Columns: customdomain.AuthorizedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &CustomDomainUserCreate{config: _u.config, mutation: newCustomDomainUserMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AuthorizedUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   customdomain.AuthorizedUsersTable,
			Columns: customdomain.AuthorizedUsersPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		createE := &CustomDomainUserCreate{config: _u.config, mutation: newCustomDomainUserMutation(_u.config, OpCreate)}
		createE.defaults()
		_, specE := createE.createSpec()
		edge.Target.Fields = specE.Fields
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &CustomDomain{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customdomain.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
