// Code generated by ent, DO NOT EDIT.

package customdomain

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the customdomain type in the database.
	Label = "custom_domain"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAllUsers holds the string denoting the all_users field in the database.
	FieldAllUsers = "all_users"
	// FieldDomain holds the string denoting the domain field in the database.
	FieldDomain = "domain"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldVerificationToken holds the string denoting the verification_token field in the database.
	FieldVerificationToken = "verification_token"
	// FieldVerificationTxtName holds the string denoting the verification_txt_name field in the database.
	FieldVerificationTxtName = "verification_txt_name"
	// FieldVerificationTxtValue holds the string denoting the verification_txt_value field in the database.
	FieldVerificationTxtValue = "verification_txt_value"
	// FieldCnameTarget holds the string denoting the cname_target field in the database.
	FieldCnameTarget = "cname_target"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldVerifiedAt holds the string denoting the verified_at field in the database.
	FieldVerifiedAt = "verified_at"
	// FieldLastCheckedAt holds the string denoting the last_checked_at field in the database.
	FieldLastCheckedAt = "last_checked_at"
	// FieldDisabledAt holds the string denoting the disabled_at field in the database.
	FieldDisabledAt = "disabled_at"
	// FieldDisabledReason holds the string denoting the disabled_reason field in the database.
	FieldDisabledReason = "disabled_reason"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeAuthorizedUsers holds the string denoting the authorized_users edge name in mutations.
	EdgeAuthorizedUsers = "authorized_users"
	// EdgeCustomDomainUsers holds the string denoting the custom_domain_users edge name in mutations.
	EdgeCustomDomainUsers = "custom_domain_users"
	// Table holds the table name of the customdomain in the database.
	Table = "custom_domains"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "custom_domains"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// AuthorizedUsersTable is the table that holds the authorized_users relation/edge. The primary key declared below.
	AuthorizedUsersTable = "custom_domain_users"
	// AuthorizedUsersInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AuthorizedUsersInverseTable = "users"
	// CustomDomainUsersTable is the table that holds the custom_domain_users relation/edge.
	CustomDomainUsersTable = "custom_domain_users"
	// CustomDomainUsersInverseTable is the table name for the CustomDomainUser entity.
	// It exists in this package in order to avoid circular dependency with the "customdomainuser" package.
	CustomDomainUsersInverseTable = "custom_domain_users"
	// CustomDomainUsersColumn is the table column denoting the custom_domain_users relation/edge.
	CustomDomainUsersColumn = "custom_domain_id"
)

// Columns holds all SQL columns for customdomain fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldUserID,
	FieldAllUsers,
	FieldDomain,
	FieldStatus,
	FieldVerificationToken,
	FieldVerificationTxtName,
	FieldVerificationTxtValue,
	FieldCnameTarget,
	FieldLastError,
	FieldVerifiedAt,
	FieldLastCheckedAt,
	FieldDisabledAt,
	FieldDisabledReason,
}

var (
	// AuthorizedUsersPrimaryKey and AuthorizedUsersColumn2 are the table columns denoting the
	// primary key for the authorized_users relation (M2M).
	AuthorizedUsersPrimaryKey = []string{"custom_domain_id", "user_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultAllUsers holds the default value on creation for the "all_users" field.
	DefaultAllUsers bool
	// DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	DomainValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// VerificationTokenValidator is a validator for the "verification_token" field. It is called by the builders before save.
	VerificationTokenValidator func(string) error
	// VerificationTxtNameValidator is a validator for the "verification_txt_name" field. It is called by the builders before save.
	VerificationTxtNameValidator func(string) error
	// VerificationTxtValueValidator is a validator for the "verification_txt_value" field. It is called by the builders before save.
	VerificationTxtValueValidator func(string) error
	// CnameTargetValidator is a validator for the "cname_target" field. It is called by the builders before save.
	CnameTargetValidator func(string) error
)

// OrderOption defines the ordering options for the CustomDomain queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAllUsers orders the results by the all_users field.
func ByAllUsers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllUsers, opts...).ToFunc()
}

// ByDomain orders the results by the domain field.
func ByDomain(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDomain, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByVerificationToken orders the results by the verification_token field.
func ByVerificationToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerificationToken, opts...).ToFunc()
}

// ByVerificationTxtName orders the results by the verification_txt_name field.
func ByVerificationTxtName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerificationTxtName, opts...).ToFunc()
}

// ByVerificationTxtValue orders the results by the verification_txt_value field.
func ByVerificationTxtValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerificationTxtValue, opts...).ToFunc()
}

// ByCnameTarget orders the results by the cname_target field.
func ByCnameTarget(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCnameTarget, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByVerifiedAt orders the results by the verified_at field.
func ByVerifiedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVerifiedAt, opts...).ToFunc()
}

// ByLastCheckedAt orders the results by the last_checked_at field.
func ByLastCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCheckedAt, opts...).ToFunc()
}

// ByDisabledAt orders the results by the disabled_at field.
func ByDisabledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisabledAt, opts...).ToFunc()
}

// ByDisabledReason orders the results by the disabled_reason field.
func ByDisabledReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisabledReason, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByAuthorizedUsersCount orders the results by authorized_users count.
func ByAuthorizedUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAuthorizedUsersStep(), opts...)
	}
}

// ByAuthorizedUsers orders the results by authorized_users terms.
func ByAuthorizedUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuthorizedUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCustomDomainUsersCount orders the results by custom_domain_users count.
func ByCustomDomainUsersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCustomDomainUsersStep(), opts...)
	}
}

// ByCustomDomainUsers orders the results by custom_domain_users terms.
func ByCustomDomainUsers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCustomDomainUsersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newAuthorizedUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuthorizedUsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, false, AuthorizedUsersTable, AuthorizedUsersPrimaryKey...),
	)
}
func newCustomDomainUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CustomDomainUsersInverseTable, CustomDomainUsersColumn),
		sqlgraph.Edge(sqlgraph.O2M, true, CustomDomainUsersTable, CustomDomainUsersColumn),
	)
}
