// Code generated by ent, DO NOT EDIT.

package customdomain

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldUserID, v))
}

// Domain applies equality check predicate on the "domain" field. It's identical to DomainEQ.
func Domain(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldDomain, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldStatus, v))
}

// VerificationToken applies equality check predicate on the "verification_token" field. It's identical to VerificationTokenEQ.
func VerificationToken(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldVerificationToken, v))
}

// VerificationTxtName applies equality check predicate on the "verification_txt_name" field. It's identical to VerificationTxtNameEQ.
func VerificationTxtName(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldVerificationTxtName, v))
}

// VerificationTxtValue applies equality check predicate on the "verification_txt_value" field. It's identical to VerificationTxtValueEQ.
func VerificationTxtValue(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldVerificationTxtValue, v))
}

// CnameTarget applies equality check predicate on the "cname_target" field. It's identical to CnameTargetEQ.
func CnameTarget(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldCnameTarget, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldLastError, v))
}

// VerifiedAt applies equality check predicate on the "verified_at" field. It's identical to VerifiedAtEQ.
func VerifiedAt(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldVerifiedAt, v))
}

// LastCheckedAt applies equality check predicate on the "last_checked_at" field. It's identical to LastCheckedAtEQ.
func LastCheckedAt(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldLastCheckedAt, v))
}

// DisabledAt applies equality check predicate on the "disabled_at" field. It's identical to DisabledAtEQ.
func DisabledAt(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldDisabledAt, v))
}

// DisabledReason applies equality check predicate on the "disabled_reason" field. It's identical to DisabledReasonEQ.
func DisabledReason(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldDisabledReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotIn(FieldUserID, vs...))
}

// DomainEQ applies the EQ predicate on the "domain" field.
func DomainEQ(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldDomain, v))
}

// DomainNEQ applies the NEQ predicate on the "domain" field.
func DomainNEQ(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNEQ(FieldDomain, v))
}

// DomainIn applies the In predicate on the "domain" field.
func DomainIn(vs ...string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIn(FieldDomain, vs...))
}

// DomainNotIn applies the NotIn predicate on the "domain" field.
func DomainNotIn(vs ...string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotIn(FieldDomain, vs...))
}

// DomainGT applies the GT predicate on the "domain" field.
func DomainGT(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGT(FieldDomain, v))
}

// DomainGTE applies the GTE predicate on the "domain" field.
func DomainGTE(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGTE(FieldDomain, v))
}

// DomainLT applies the LT predicate on the "domain" field.
func DomainLT(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLT(FieldDomain, v))
}

// DomainLTE applies the LTE predicate on the "domain" field.
func DomainLTE(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLTE(FieldDomain, v))
}

// DomainContains applies the Contains predicate on the "domain" field.
func DomainContains(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldContains(FieldDomain, v))
}

// DomainHasPrefix applies the HasPrefix predicate on the "domain" field.
func DomainHasPrefix(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldHasPrefix(FieldDomain, v))
}

// DomainHasSuffix applies the HasSuffix predicate on the "domain" field.
func DomainHasSuffix(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldHasSuffix(FieldDomain, v))
}

// DomainEqualFold applies the EqualFold predicate on the "domain" field.
func DomainEqualFold(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEqualFold(FieldDomain, v))
}

// DomainContainsFold applies the ContainsFold predicate on the "domain" field.
func DomainContainsFold(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldContainsFold(FieldDomain, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldContainsFold(FieldStatus, v))
}

// VerificationTokenEQ applies the EQ predicate on the "verification_token" field.
func VerificationTokenEQ(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldVerificationToken, v))
}

// VerificationTokenNEQ applies the NEQ predicate on the "verification_token" field.
func VerificationTokenNEQ(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNEQ(FieldVerificationToken, v))
}

// VerificationTokenIn applies the In predicate on the "verification_token" field.
func VerificationTokenIn(vs ...string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIn(FieldVerificationToken, vs...))
}

// VerificationTokenNotIn applies the NotIn predicate on the "verification_token" field.
func VerificationTokenNotIn(vs ...string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotIn(FieldVerificationToken, vs...))
}

// VerificationTokenGT applies the GT predicate on the "verification_token" field.
func VerificationTokenGT(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGT(FieldVerificationToken, v))
}

// VerificationTokenGTE applies the GTE predicate on the "verification_token" field.
func VerificationTokenGTE(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGTE(FieldVerificationToken, v))
}

// VerificationTokenLT applies the LT predicate on the "verification_token" field.
func VerificationTokenLT(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLT(FieldVerificationToken, v))
}

// VerificationTokenLTE applies the LTE predicate on the "verification_token" field.
func VerificationTokenLTE(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLTE(FieldVerificationToken, v))
}

// VerificationTokenContains applies the Contains predicate on the "verification_token" field.
func VerificationTokenContains(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldContains(FieldVerificationToken, v))
}

// VerificationTokenHasPrefix applies the HasPrefix predicate on the "verification_token" field.
func VerificationTokenHasPrefix(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldHasPrefix(FieldVerificationToken, v))
}

// VerificationTokenHasSuffix applies the HasSuffix predicate on the "verification_token" field.
func VerificationTokenHasSuffix(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldHasSuffix(FieldVerificationToken, v))
}

// VerificationTokenEqualFold applies the EqualFold predicate on the "verification_token" field.
func VerificationTokenEqualFold(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEqualFold(FieldVerificationToken, v))
}

// VerificationTokenContainsFold applies the ContainsFold predicate on the "verification_token" field.
func VerificationTokenContainsFold(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldContainsFold(FieldVerificationToken, v))
}

// VerificationTxtNameEQ applies the EQ predicate on the "verification_txt_name" field.
func VerificationTxtNameEQ(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldVerificationTxtName, v))
}

// VerificationTxtNameNEQ applies the NEQ predicate on the "verification_txt_name" field.
func VerificationTxtNameNEQ(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNEQ(FieldVerificationTxtName, v))
}

// VerificationTxtNameIn applies the In predicate on the "verification_txt_name" field.
func VerificationTxtNameIn(vs ...string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIn(FieldVerificationTxtName, vs...))
}

// VerificationTxtNameNotIn applies the NotIn predicate on the "verification_txt_name" field.
func VerificationTxtNameNotIn(vs ...string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotIn(FieldVerificationTxtName, vs...))
}

// VerificationTxtNameGT applies the GT predicate on the "verification_txt_name" field.
func VerificationTxtNameGT(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGT(FieldVerificationTxtName, v))
}

// VerificationTxtNameGTE applies the GTE predicate on the "verification_txt_name" field.
func VerificationTxtNameGTE(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGTE(FieldVerificationTxtName, v))
}

// VerificationTxtNameLT applies the LT predicate on the "verification_txt_name" field.
func VerificationTxtNameLT(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLT(FieldVerificationTxtName, v))
}

// VerificationTxtNameLTE applies the LTE predicate on the "verification_txt_name" field.
func VerificationTxtNameLTE(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLTE(FieldVerificationTxtName, v))
}

// VerificationTxtNameContains applies the Contains predicate on the "verification_txt_name" field.
func VerificationTxtNameContains(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldContains(FieldVerificationTxtName, v))
}

// VerificationTxtNameHasPrefix applies the HasPrefix predicate on the "verification_txt_name" field.
func VerificationTxtNameHasPrefix(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldHasPrefix(FieldVerificationTxtName, v))
}

// VerificationTxtNameHasSuffix applies the HasSuffix predicate on the "verification_txt_name" field.
func VerificationTxtNameHasSuffix(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldHasSuffix(FieldVerificationTxtName, v))
}

// VerificationTxtNameEqualFold applies the EqualFold predicate on the "verification_txt_name" field.
func VerificationTxtNameEqualFold(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEqualFold(FieldVerificationTxtName, v))
}

// VerificationTxtNameContainsFold applies the ContainsFold predicate on the "verification_txt_name" field.
func VerificationTxtNameContainsFold(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldContainsFold(FieldVerificationTxtName, v))
}

// VerificationTxtValueEQ applies the EQ predicate on the "verification_txt_value" field.
func VerificationTxtValueEQ(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldVerificationTxtValue, v))
}

// VerificationTxtValueNEQ applies the NEQ predicate on the "verification_txt_value" field.
func VerificationTxtValueNEQ(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNEQ(FieldVerificationTxtValue, v))
}

// VerificationTxtValueIn applies the In predicate on the "verification_txt_value" field.
func VerificationTxtValueIn(vs ...string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIn(FieldVerificationTxtValue, vs...))
}

// VerificationTxtValueNotIn applies the NotIn predicate on the "verification_txt_value" field.
func VerificationTxtValueNotIn(vs ...string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotIn(FieldVerificationTxtValue, vs...))
}

// VerificationTxtValueGT applies the GT predicate on the "verification_txt_value" field.
func VerificationTxtValueGT(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGT(FieldVerificationTxtValue, v))
}

// VerificationTxtValueGTE applies the GTE predicate on the "verification_txt_value" field.
func VerificationTxtValueGTE(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGTE(FieldVerificationTxtValue, v))
}

// VerificationTxtValueLT applies the LT predicate on the "verification_txt_value" field.
func VerificationTxtValueLT(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLT(FieldVerificationTxtValue, v))
}

// VerificationTxtValueLTE applies the LTE predicate on the "verification_txt_value" field.
func VerificationTxtValueLTE(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLTE(FieldVerificationTxtValue, v))
}

// VerificationTxtValueContains applies the Contains predicate on the "verification_txt_value" field.
func VerificationTxtValueContains(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldContains(FieldVerificationTxtValue, v))
}

// VerificationTxtValueHasPrefix applies the HasPrefix predicate on the "verification_txt_value" field.
func VerificationTxtValueHasPrefix(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldHasPrefix(FieldVerificationTxtValue, v))
}

// VerificationTxtValueHasSuffix applies the HasSuffix predicate on the "verification_txt_value" field.
func VerificationTxtValueHasSuffix(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldHasSuffix(FieldVerificationTxtValue, v))
}

// VerificationTxtValueEqualFold applies the EqualFold predicate on the "verification_txt_value" field.
func VerificationTxtValueEqualFold(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEqualFold(FieldVerificationTxtValue, v))
}

// VerificationTxtValueContainsFold applies the ContainsFold predicate on the "verification_txt_value" field.
func VerificationTxtValueContainsFold(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldContainsFold(FieldVerificationTxtValue, v))
}

// CnameTargetEQ applies the EQ predicate on the "cname_target" field.
func CnameTargetEQ(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldCnameTarget, v))
}

// CnameTargetNEQ applies the NEQ predicate on the "cname_target" field.
func CnameTargetNEQ(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNEQ(FieldCnameTarget, v))
}

// CnameTargetIn applies the In predicate on the "cname_target" field.
func CnameTargetIn(vs ...string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIn(FieldCnameTarget, vs...))
}

// CnameTargetNotIn applies the NotIn predicate on the "cname_target" field.
func CnameTargetNotIn(vs ...string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotIn(FieldCnameTarget, vs...))
}

// CnameTargetGT applies the GT predicate on the "cname_target" field.
func CnameTargetGT(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGT(FieldCnameTarget, v))
}

// CnameTargetGTE applies the GTE predicate on the "cname_target" field.
func CnameTargetGTE(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGTE(FieldCnameTarget, v))
}

// CnameTargetLT applies the LT predicate on the "cname_target" field.
func CnameTargetLT(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLT(FieldCnameTarget, v))
}

// CnameTargetLTE applies the LTE predicate on the "cname_target" field.
func CnameTargetLTE(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLTE(FieldCnameTarget, v))
}

// CnameTargetContains applies the Contains predicate on the "cname_target" field.
func CnameTargetContains(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldContains(FieldCnameTarget, v))
}

// CnameTargetHasPrefix applies the HasPrefix predicate on the "cname_target" field.
func CnameTargetHasPrefix(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldHasPrefix(FieldCnameTarget, v))
}

// CnameTargetHasSuffix applies the HasSuffix predicate on the "cname_target" field.
func CnameTargetHasSuffix(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldHasSuffix(FieldCnameTarget, v))
}

// CnameTargetIsNil applies the IsNil predicate on the "cname_target" field.
func CnameTargetIsNil() predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIsNull(FieldCnameTarget))
}

// CnameTargetNotNil applies the NotNil predicate on the "cname_target" field.
func CnameTargetNotNil() predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotNull(FieldCnameTarget))
}

// CnameTargetEqualFold applies the EqualFold predicate on the "cname_target" field.
func CnameTargetEqualFold(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEqualFold(FieldCnameTarget, v))
}

// CnameTargetContainsFold applies the ContainsFold predicate on the "cname_target" field.
func CnameTargetContainsFold(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldContainsFold(FieldCnameTarget, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldContainsFold(FieldLastError, v))
}

// VerifiedAtEQ applies the EQ predicate on the "verified_at" field.
func VerifiedAtEQ(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldVerifiedAt, v))
}

// VerifiedAtNEQ applies the NEQ predicate on the "verified_at" field.
func VerifiedAtNEQ(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNEQ(FieldVerifiedAt, v))
}

// VerifiedAtIn applies the In predicate on the "verified_at" field.
func VerifiedAtIn(vs ...time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIn(FieldVerifiedAt, vs...))
}

// VerifiedAtNotIn applies the NotIn predicate on the "verified_at" field.
func VerifiedAtNotIn(vs ...time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotIn(FieldVerifiedAt, vs...))
}

// VerifiedAtGT applies the GT predicate on the "verified_at" field.
func VerifiedAtGT(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGT(FieldVerifiedAt, v))
}

// VerifiedAtGTE applies the GTE predicate on the "verified_at" field.
func VerifiedAtGTE(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGTE(FieldVerifiedAt, v))
}

// VerifiedAtLT applies the LT predicate on the "verified_at" field.
func VerifiedAtLT(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLT(FieldVerifiedAt, v))
}

// VerifiedAtLTE applies the LTE predicate on the "verified_at" field.
func VerifiedAtLTE(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLTE(FieldVerifiedAt, v))
}

// VerifiedAtIsNil applies the IsNil predicate on the "verified_at" field.
func VerifiedAtIsNil() predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIsNull(FieldVerifiedAt))
}

// VerifiedAtNotNil applies the NotNil predicate on the "verified_at" field.
func VerifiedAtNotNil() predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotNull(FieldVerifiedAt))
}

// LastCheckedAtEQ applies the EQ predicate on the "last_checked_at" field.
func LastCheckedAtEQ(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtNEQ applies the NEQ predicate on the "last_checked_at" field.
func LastCheckedAtNEQ(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtIn applies the In predicate on the "last_checked_at" field.
func LastCheckedAtIn(vs ...time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtNotIn applies the NotIn predicate on the "last_checked_at" field.
func LastCheckedAtNotIn(vs ...time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtGT applies the GT predicate on the "last_checked_at" field.
func LastCheckedAtGT(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGT(FieldLastCheckedAt, v))
}

// LastCheckedAtGTE applies the GTE predicate on the "last_checked_at" field.
func LastCheckedAtGTE(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGTE(FieldLastCheckedAt, v))
}

// LastCheckedAtLT applies the LT predicate on the "last_checked_at" field.
func LastCheckedAtLT(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLT(FieldLastCheckedAt, v))
}

// LastCheckedAtLTE applies the LTE predicate on the "last_checked_at" field.
func LastCheckedAtLTE(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLTE(FieldLastCheckedAt, v))
}

// LastCheckedAtIsNil applies the IsNil predicate on the "last_checked_at" field.
func LastCheckedAtIsNil() predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIsNull(FieldLastCheckedAt))
}

// LastCheckedAtNotNil applies the NotNil predicate on the "last_checked_at" field.
func LastCheckedAtNotNil() predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotNull(FieldLastCheckedAt))
}

// DisabledAtEQ applies the EQ predicate on the "disabled_at" field.
func DisabledAtEQ(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldDisabledAt, v))
}

// DisabledAtNEQ applies the NEQ predicate on the "disabled_at" field.
func DisabledAtNEQ(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNEQ(FieldDisabledAt, v))
}

// DisabledAtIn applies the In predicate on the "disabled_at" field.
func DisabledAtIn(vs ...time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIn(FieldDisabledAt, vs...))
}

// DisabledAtNotIn applies the NotIn predicate on the "disabled_at" field.
func DisabledAtNotIn(vs ...time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotIn(FieldDisabledAt, vs...))
}

// DisabledAtGT applies the GT predicate on the "disabled_at" field.
func DisabledAtGT(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGT(FieldDisabledAt, v))
}

// DisabledAtGTE applies the GTE predicate on the "disabled_at" field.
func DisabledAtGTE(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGTE(FieldDisabledAt, v))
}

// DisabledAtLT applies the LT predicate on the "disabled_at" field.
func DisabledAtLT(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLT(FieldDisabledAt, v))
}

// DisabledAtLTE applies the LTE predicate on the "disabled_at" field.
func DisabledAtLTE(v time.Time) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLTE(FieldDisabledAt, v))
}

// DisabledAtIsNil applies the IsNil predicate on the "disabled_at" field.
func DisabledAtIsNil() predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIsNull(FieldDisabledAt))
}

// DisabledAtNotNil applies the NotNil predicate on the "disabled_at" field.
func DisabledAtNotNil() predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotNull(FieldDisabledAt))
}

// DisabledReasonEQ applies the EQ predicate on the "disabled_reason" field.
func DisabledReasonEQ(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEQ(FieldDisabledReason, v))
}

// DisabledReasonNEQ applies the NEQ predicate on the "disabled_reason" field.
func DisabledReasonNEQ(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNEQ(FieldDisabledReason, v))
}

// DisabledReasonIn applies the In predicate on the "disabled_reason" field.
func DisabledReasonIn(vs ...string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIn(FieldDisabledReason, vs...))
}

// DisabledReasonNotIn applies the NotIn predicate on the "disabled_reason" field.
func DisabledReasonNotIn(vs ...string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotIn(FieldDisabledReason, vs...))
}

// DisabledReasonGT applies the GT predicate on the "disabled_reason" field.
func DisabledReasonGT(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGT(FieldDisabledReason, v))
}

// DisabledReasonGTE applies the GTE predicate on the "disabled_reason" field.
func DisabledReasonGTE(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldGTE(FieldDisabledReason, v))
}

// DisabledReasonLT applies the LT predicate on the "disabled_reason" field.
func DisabledReasonLT(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLT(FieldDisabledReason, v))
}

// DisabledReasonLTE applies the LTE predicate on the "disabled_reason" field.
func DisabledReasonLTE(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldLTE(FieldDisabledReason, v))
}

// DisabledReasonContains applies the Contains predicate on the "disabled_reason" field.
func DisabledReasonContains(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldContains(FieldDisabledReason, v))
}

// DisabledReasonHasPrefix applies the HasPrefix predicate on the "disabled_reason" field.
func DisabledReasonHasPrefix(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldHasPrefix(FieldDisabledReason, v))
}

// DisabledReasonHasSuffix applies the HasSuffix predicate on the "disabled_reason" field.
func DisabledReasonHasSuffix(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldHasSuffix(FieldDisabledReason, v))
}

// DisabledReasonIsNil applies the IsNil predicate on the "disabled_reason" field.
func DisabledReasonIsNil() predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldIsNull(FieldDisabledReason))
}

// DisabledReasonNotNil applies the NotNil predicate on the "disabled_reason" field.
func DisabledReasonNotNil() predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldNotNull(FieldDisabledReason))
}

// DisabledReasonEqualFold applies the EqualFold predicate on the "disabled_reason" field.
func DisabledReasonEqualFold(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldEqualFold(FieldDisabledReason, v))
}

// DisabledReasonContainsFold applies the ContainsFold predicate on the "disabled_reason" field.
func DisabledReasonContainsFold(v string) predicate.CustomDomain {
	return predicate.CustomDomain(sql.FieldContainsFold(FieldDisabledReason, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.CustomDomain {
	return predicate.CustomDomain(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.CustomDomain {
	return predicate.CustomDomain(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CustomDomain) predicate.CustomDomain {
	return predicate.CustomDomain(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CustomDomain) predicate.CustomDomain {
	return predicate.CustomDomain(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CustomDomain) predicate.CustomDomain {
	return predicate.CustomDomain(sql.NotPredicates(p))
}
